### PR TITLE
Rename/deprecate num_signatures to num_total_signatures

### PR DESCRIPTION
**Pull request by apfitzge**
#### Problem
- The `num_signatures` function name is confusing since it includes "actual" signatures on the transaction, as well as "pre-compile" signatures that are attached as instructions.

#### Summary of Changes
- deprecate `SantizedMessage::num_signatures`
- add new function `SanitizedMessage::num_total_signatures`
- rename `SVMMessage::num_signatures` to `SVMMessage::num_total_signatures` to match

Fixes #

### CODE REVIEW

**Comment by apfitzge** [comment]
Noticed this odd/misleading naming when working on stuff related to #1918

**Comment by apfitzge** [comment]
Have not deprecated anything in SDK before; is this the correct way to do it?

**Review by bw-solana — APPROVED** [review]
This looks correct to me. Should wait for @buffalojoec to confirm before merging

**Comment by apfitzge** [comment]
Want to use the new name in #2125; because we need a way to distinguish so that we get the right number to inspect the `Signature`s on transaction.

**Review by buffalojoec — APPROVED** [review]

**Pull request merged**
