### PR TITLE
Removing saturating_add_assign and replacing with Saturating struct

### PR DESCRIPTION
**Pull request by roryharr**
#### Problem
Cleaning up all usages of saturating add assign and replacing with Saturating
https://github.com/anza-xyz/agave/issues/502

#### Summary of Changes

Fixes #

### CODE REVIEW

**Review by steviez — DISMISSED** [review]
Thank, LGTM! I applied the CI label but we'll also need to let someone from svm team take a look too

**Review by LucasSte — DISMISSED** [review]

**Comment by LucasSte** [comment]
The CI has been failing in a check: https://buildkite.com/anza/agave/builds/15596#0193af2b-68f5-4b10-84d9-f316e42f9886

Would you mind fixing that?

**Comment by roryharr** [comment]
> The CI has been failing in a check: https://buildkite.com/anza/agave/builds/15596#0193af2b-68f5-4b10-84d9-f316e42f9886
> 
> Would you mind fixing that?

Resolved

**Comment by roryharr** [comment]
Clippy failure as well. Will grab that, and run locally from now on.

**Comment by steviez** [comment]
In the future, the following are good command to run from the base of the repo:
```
$ ./cargo nightly fmt
$ ./cargo nightly clippy
$ cargo test --no-run
```
The first two will keep the linters happy, the last one will ensure all test code can be compiled oto

**Comment by roryharr** [comment]
Clippy nightly has a bunch of errors right now that seem unrelated. Is there a set of rules that should be ignored?
For example:
<noformat>
warning: the following explicit lifetimes could be elided: 'a
  --> core/src/repair/repair_generic_traversal.rs:25:6
   |
25 | impl<'a> Iterator for GenericTraversal<'a> {
   |      ^^                                ^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
help: elide the lifetimes
   |
25 - impl<'a> Iterator for GenericTraversal<'a> {
25 + impl Iterator for GenericTraversal<'_> {
<noformat>

**Comment by steviez** [comment]
> Clippy nightly has a bunch of errors right now that seem unrelated. Is there a set of rules that should be ignored? For example: warning: the following explicit lifetimes could be elided: 'a --> core/src/repair/repair_generic_traversal.rs:25:6 | 25 | impl<'a> Iterator for GenericTraversal<'a> { | ^^ ^^ | = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes help: elide the lifetimes | 25 - impl<'a> Iterator for GenericTraversal<'a> { 25 + impl Iterator for GenericTraversal<'_> {

Are you sure you're using the correct nightly version ? If you use the one specified by `./cargo nightly`, then that should build with what we build with. For the [specific failure you hit this time](https://buildkite.com/anza/agave/builds/15651#0193b1ca-35e0-4f8e-a6a5-7414b081b03c
), you need to rebase to tip of master to pick up https://github.com/anza-xyz/agave/pull/4023:
```
error: this function has too many arguments (10/9)
--
  | --> accounts-cluster-bench/src/main.rs:749:1
  | \|
  | 749 \| / fn make_rpc_bench_threads(
  | 750 \| \|     rpc_benches: Vec<RpcBench>,
  | 751 \| \|     mint: &Option<Pubkey>,
  | 752 \| \|     start_bench_barrier: &Arc<Barrier>,
  | ...   \|
  | 759 \| \|     transaction_signature_tracker: &TransactionSignatureTracker,
  | 760 \| \| ) -> Vec<JoinHandle<()>> {
```

**Comment by roryharr** [comment]
Thanks, I see the issue. I was using cargo +nightly, rather than ./cargo nightly

**Comment by steviez** [comment]
As another note - when you make changes to the PR, please push them as new commits instead of squashing them down.
- If you push new commits, it is easier to see the couple lines that you have changed
- If you squash everything together, we have to re-review the entire changeset

**Comment by roryharr** [comment]
Thanks, sorry about that. It was a requirement where I previously worked. 

Will take a look at the coverage build failures. 

failures:
---- commands::tests::test_distribute_allocations_dump_db stdout ----
thread 'commands::tests::test_distribute_allocations_dump_db' panicked at test-validator/src/lib.rs:723:14:
validator start failed: Address already in use (os error 98)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Review by steviez — APPROVED** [review]
> Thanks, sorry about that. It was a requirement where I previously worked.
> 
> Will take a look at the coverage build failures.
> 
> failures: ---- commands::tests::test_distribute_allocations_dump_db stdout ---- thread 'commands::tests::test_distribute_allocations_dump_db' panicked at test-validator/src/lib.rs:723:14: validator start failed: Address already in use (os error 98) note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This failure looks unrelated and seemingly a flaky test; I retried the test and it passed. Thanks for the contribution

**Review by LucasSte — APPROVED** [review]

**Pull request merged**
