### PR TITLE
snapshot/don't flush accounts file when taking snapshots

### PR DESCRIPTION
**Pull request by HaoranYi**
#### Problem

In https://github.com/anza-xyz/agave/pull/1430, we found that mmap flush caused
larger accounts files on disk (due to alignment padding). This results in
larger snapshot files. 

Since we have switched to archive mmap direct from in-memory representation.
There is no longer a need to flush the mmap.

image

By removing flush, we could reduce the snapshot timing by 2-7s.

#### Summary of Changes

- don't flush mmap when taking snapshots

Fixes #

### CODE REVIEW

**Review by brooksprumo — COMMENTED** [review]
We must flush the mmaps to disk otherwise fastboot will fail.

**Comment by HaoranYi** [comment]
Good point. But, I wonder, when a process crashes or exits, will the OS automatically writes the dirty pages from mmap to disk?

**Comment by HaoranYi** [comment]
Or, though the dirty pages are not flushed in to the disk, they stay in the kernel file system buffer. When the process restarts and remmap those files, the kernel file system will know to recycle the dirty pages from the kernel file system buffer?

**Comment by brooksprumo** [comment]
> Or, though the dirty pages are not flushed in to the disk, they stay in the kernel file system buffer. When the process restarts and remmap those files, the kernel file system will know to recycle the dirty pages from the kernel file system buffer?

I'm not sure? Maybe? I'm also concerned about a failure that causes the machine to lose power. When the validator restarts, we'd need a way to know if the local state is safer or not to fastboot from. Maybe that's possible? I'm not sure how to do that currently.

**Comment by HaoranYi** [comment]
When machine loses power during flush(), the file on disk can also be bad. We won't be able to fastboot in this case. 

I am rebasing to master to pick up your fix of accounts hash during serialization. 
I will try to start a validator and test how fastboot works with this PR. ;-)

**Comment by brooksprumo** [comment]
Flushing is required to support fastboot. If we don't flush, sometimes fastboot may still work if the OS did actually flush. But it's not guaranteed. 

Alessandro and I have talked about changing the fastboot behavior to be only supported on graceful shutdown. This would remove the need to flush except when shutting down. We need to get buy-in/OK'd before changing this behavior though.

Another option is to add a field to AppendVec/AccountStorageEntry/etc that is a bool if we've flushed before or not. Now that the recycler is removed, once we flush once, we never need to flush again. This way we can reduce the number of files that we actually flush to only the new storage files.

**Comment by HaoranYi** [comment]
I have been running an experiment on my node with this PR by not flushing mmap when taking snapshot for the past few days. 

I setup up a cron job to restart my validator every hour with fast boot. So far, my validator has been restarted with fast boot for 139 times. And all restarts succeeded!

Maybe, it is just that we are lucy all the time.

Or maybe when the validator process exits, it will flush mmap when we unmap the mmap?

**Comment by brooksprumo** [comment]
> Maybe, it is just that we are lucy all the time.

This is what I most worry about. There's not a *guarantee* that the mmap will be flushed if we don't call it explicitly. Is it likely? That appears to be yes. It does make me uncomfortable though.


> Or maybe when the validator process exits, it will flush mmap when we unmap the mmap?

You mean in the OS? That part I don't know about. Maybe? Is there a guarantee? Is there a guarantee the OS would flush to disk *before* restart the validator the next time? Does it matter? Would the mmap still be in the OS's memory, and if it got mapped back it, would it just re-use what's in the OS's memory?

What about on a power cycle? I would argue that this is a use-case we should *not* support, but currently we do. This is part of the behavior change I was referring to.

At least in the validator code itself, we do not flush when dropping mmaps. The change I would like to make would be that we only call flush when the shared `exit` flag goes true. This actually happens more some fatal errors too; just not panics. And not power failures.

**Comment by HaoranYi** [comment]
> The change I would like to make would be that we only call flush when the shared exit flag goes true. This actually happens more some fatal errors too; just not panics. And not power failures.

I like this idea.

**Comment by HaoranYi** [comment]
I found an interesting remark about mmap from posix documentation. 

"MAP_SHARED and MAP_PRIVATE describe the disposition of write references to the memory object. If MAP_SHARED is specified, write references shall change the underlying object."

- https://pubs.opengroup.org/onlinepubs/9699919799/toc.htm

The way our validator opens mmap file is with `MAP_SHARED` mode.
- https://github.com/anza-xyz/agave/blob/master/accounts-db/src/append_vec.rs#L293
- https://github.com/RazrFalcon/memmap2-rs/blob/f7c50830ed332d4a53dd948194c87bfd3b25855b/src/unix.rs#L248

With `MAP_SHRED` mode, updates to the mapping are carried through the
underlying file. 
- https://man7.org/linux/man-pages/man2/mmap.2.html

Also, there is a post on stackoverflow to indicate that 

"It looks like that the kernel buffer pool will write the dirty pages to disk -
regardless of the cause of crash."

https://stackoverflow.com/questions/863523/does-the-os-posix-flush-a-memory-mapped-file-if-the-process-is-sigkilled

I believe that this would explain why my 139 fast boot always succeed.

The reason that we need to flush before is for archiving snapshot from disk, which forces a msync of the disk by this time to make sure that the archive process read the updated data. Now we archive directly from memory. We don't need to force the exact timing of msync. For fast boot, we only need that the mmap is write to the disk, which shall already covered by the fact that we open mmap with "MAP_SHARED" flag.

**Comment by brooksprumo** [comment]
> I found an interesting remark [..]

This is *very* interesting! Almost sounds too good to be true. So we don't need to ever call `flush` on the mmap then?

@alessandrod Can I get your thoughts on what @HaoranYi wrote in the previous comment? Maybe we never need to flush?

**Comment by HaoranYi** [comment]
>  So we don't need to ever call flush on the mmap then?

When we do archive from disk, we need to flush. OS will write MAP_SHARED to disk but don't specify *when*. That's why we need to call flush, before archiving, to make sure that the archive process read the updated data from disk. But for fastboot, we have no such timing requirement. Therefore, we don't need to call flush.

**Comment by HaoranYi** [comment]
Use #1676 instead.

**Pull request closed without merging**
