### PR TITLE
Add support for Ledger Flex

### PR DESCRIPTION
**Pull request by Managarmrr**
This PR adds support for the new ledger flex with the cli.

#### Problem

The new ledger flex was currently not supported by the cli.

#### Summary of Changes

The ledger flex product ids have been added to the solana-remote-wallet crate.

### CODE REVIEW

**Comment by steviez** [comment]
@t-nelson - Am I remembering correctly that you're the expert on this piece ?

**Review by t-nelson — APPROVED** [review]

**Comment by M-R-DUCK** [comment]
Also please add Ledger STAX

**Comment by pgarg66** [comment]
> Also please add Ledger STAX

Would you like to create a PR? We can review it.

**Comment by rogaldh** [comment]
Here it is: https://github.com/anza-xyz/agave/pull/4163

**Pull request merged**
