### PR TITLE
chore: add CODEOWNERS

### PR DESCRIPTION
**Pull request by yihau**
#### Problem

we would like to loop more people to keep eyes on backport PRs.

#### Summary of Changes

introduce code owner mechanism

#### After The Merge

- [x] backport to v1.17, v1.18
- [ ] turn on the protection

### CODE REVIEW

**Comment by t-nelson** [comment]
this just specifies that the corresponding teams own all of the code, actual protection is out-of-band in github branch protection rules?

**Comment by softalchemy** [comment]
yes, we need to define the code owners so we can reference them in the branch protection rules to block on approval

**Comment by yihau** [comment]
yeah, as Joe mentioned. however there is a fun fact that it is a "or" condition. basically, if one of the team members approves, then we pass the codeowners rule. I will increase the approval counts to do the trick.

Screenshot 2024-04-23 at 12 36 51

--- 
ref: https://github.com/orgs/community/discussions/22522#discussioncomment-3237158

**Review by CriesofCarrots — APPROVED** [review]
Looks right to me

**Comment by t-nelson** [comment]
> yeah, as Joe mentioned. however there is a fun fact that it is a "or" condition. basically, if one of the team members approves, then we pass the codeowners rule. I will increase the approval counts to do the trick.
> Screenshot 2024-04-23 at 12 36 51
> 
> ref: https://github.com/orgs/community/discussions/22522#discussioncomment-3237158

that's annoying... i guess we have to manage this socially or do something like, "programmatically manage our fine grain approvals, then signal branch protection approval with a service account," if we want to logically AND approval classes?

**Review by t-nelson — APPROVED** [review]

**Comment by yihau** [comment]
looks like these two teams will be added as reviewers to all PRs. 🫠. let me check if I can do something. (However, I guess it shouldn't bother us because I bet all of us have turned on all activities notification for agave :trollface: )

ref: https://github.com/orgs/community/discussions/35673

**Pull request merged**
