### PR TITLE
chore: bump rust stable to v1.78.0, nightly to 2024-05-02

### PR DESCRIPTION
**Pull request by yihau**
#### Summary of Changes

bump Rust version

### CODE REVIEW

**Comment by yihau** [comment]
I've moved the original topic to: https://github.com/anza-xyz/agave/pull/1485

**Review by brooksprumo — APPROVED** [review]
:shipit:

**Review by steviez — APPROVED** [review]
LGTM! And I like the bulk of the work getting done in the other "setup" PR's such that this one is just a couple lines

**Review by ryoqun — APPROVED** [review]
lgtm. i don't think it's a _chore_ while the pr title says. :) great work. so glad to use the recent nightly.

**Pull request merged**
