### PR TITLE
[anza migration]: update repo url

### PR DESCRIPTION
**Pull request by michaelschem**
#### Problem

Url is set to old repo

#### Summary of Changes

Updated url

### CODE REVIEW

**Comment by michaelschem** [comment]
@CriesofCarrots similar to this one, the url needs to be updated. https://github.com/anza-xyz/agave/pull/811

**Review by buffalojoec — APPROVED** [review]
Lgtm, thanks!

**Comment by anza-team** [comment]
:scream: New commits were pushed while the automerge label was present.

**Comment by michaelschem** [comment]
@buffalojoec it seems like @chidocibot removed your tags. The second was probably my fault for re-syncing.

**Pull request merged**
