### PR TITLE
Removing all uses of saturating_add_assign from leader_slot_timing_met…

### PR DESCRIPTION
**Pull request by roryharr**
Removing all uses of saturating_add_assign from leader_slot_timing_metrics

https://github.com/anza-xyz/agave/issues/502

#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by roryharr** [comment]
Hopefully this one goes a little easier than the last!

**Review by steviez — DISMISSED** [review]
Thanks - this all looks fine to me! Pretty mechanical in nature so I don't foresee any issues, but will mention @apfitzge so he has the chance to take a look (given that this is touching code in his realm)

**Comment by apfitzge** [comment]
Not strictly opposed to this PR - it's better than the old macro...but why are we doing saturating math? (I wrote this code, so not sure there was a good reason...)

Makes no sense to me; these are microsecond timers being accumulated. we're NEVER going to see these roll over, even if they hang indefinitely (unless someone plans on running this for the next 500000 years).

@steviez thoughts on just changing these to `Wrapping`?

**Comment by roryharr** [comment]
Yeah, unless you are accumulating from multiple sources (threads, hosts etc..) these will never overflow. 

I was planing on bringing this up when cleaning up leader_slot_metrics.c, as it has worse examples:
```
saturating_add_assign!(
                leader_slot_metrics
                    .timing_metrics
                    .outer_loop_timings
                    .receive_and_buffer_packets_invoked_count,
                1);
```

**Comment by steviez** [comment]
> @steviez thoughts on just changing these to `Wrapping`?

Wrapping works for me and sounds reasonable given your explanation. In addition to killing the redundant macro, I see the following as benefits of this cleanup:
- Declaring the behavior, whether `Wrapping` or `Saturating`, in the struct exactly once which then ...
- Allows us to just use `+=` in the code and not have to remember "should I use regular, saturating, or wrapping addition here"

There may be some other cases where `Saturating` makes sense over `Wrapping`, but I agree, these seem reasonable to make `Wrapping`. Someone would seemingly have to go deliberately out of their way in order to introduce a bug that would overflow these

**Comment by roryharr** [comment]
Shouldn't they just be left as generic then? (Not saturating or wrapping). That would lead to panics in debug code, and wrapping behavior in release.

**Comment by steviez** [comment]
> Shouldn't they just be left as generic then? (Not saturating or wrapping). That would lead to panics in debug code, and wrapping behavior in release.

Lemme double check; I was acting on the assumption that integer overflow panicked in release too but I could be misremembering 😅

**Comment by steviez** [comment]
Ahh, you were correct. Here is a playground permalink where you can toggle debug/release and see debug panic / release wrap:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=11a029836c6f69bb7a5b9b80f37ed9b2

> Shouldn't they just be left as generic then?

Yeah, this sounds good to me and will avoid the annoying `.0` to get the inner `u64` for metrics reporting. Work for you @apfitzge ?

**Review by steviez — APPROVED** [review]
LGTM - Thanks for the iteration here.

For any future files you're thinking about addressing this in, feel free to drop a note in https://github.com/anza-xyz/agave/issues/502 so we can land on Satuarting/Wrapping/regular types beforehand.

**Review by apfitzge — APPROVED** [review]

**Pull request merged**
