### PR TITLE
Extend HTTP client to use reqwest with middleware

### PR DESCRIPTION
**Pull request by biryukovmaxim**
#### Problem
current HTTP client setup lacks the flexibility to efficiently capture metrics and handle errors during HTTP communications. This limitation hampers our ability to monitor, debug, etc, particularly in production environments where detailed insights and quick adaptability are crucial.

#### Summary of Changes
Client Enhancement: Modified the HttpSender class in `rpc-client/src/http_sender.rs` to use `reqwest_middleware::ClientWithMiddleware` instead of `reqwest::Client`. This change enables middleware features like request retries, logging, and metrics collection without altering the existing interface.

### CODE REVIEW

**Comment by biryukovmaxim** [comment]
@CriesofCarrots could you check it out?

**Comment by KirillLykov** [comment]
@godmodegalactus maybe you have an opinion?

**Comment by godmodegalactus** [comment]
LGTM, IMO having middleware should be optional. So if client is using custom middleware then we should use `reqwest_middleware::ClientWithMiddleware` else it should continue using `reqwest::Client`.

Other than that I am not against this change.

**Comment by biryukovmaxim** [comment]
> So if client is using custom middleware then we should use `reqwest_middleware::ClientWithMiddleware` else it should continue using `reqwest::Client`.

is has the same API as it was before, since `reqwest_middleware::ClientWithMiddleware` can be built from `reqwest::Client`. It will be 
```
/// `ClientWithMiddleware` is a wrapper around [`reqwest::Client`] which runs middleware on every
/// request.
#[derive(Clone)]
pub struct ClientWithMiddleware {
    inner: reqwest::Client,
    middleware_stack: Box<[Arc<dyn Middleware>]>,
    initialiser_stack: Box<[Arc<dyn RequestInitialiser>]>,
}
```
where stacks are empty. 
Do you mean ` HttpSender` should have Either(enum) of `reqwest::Client` or `reqwest_middleware::ClientWithMiddleware`?
I don't see a big diff in checking variant of enum against array emptyness check during processing methods  

Or do you want me to introduce generic constrainted by some trait that would be implemented for `reqwest::Client` and `reqwest_middleware::ClientWithMiddleware`?

**Comment by CriesofCarrots** [comment]
In future, please do not tag any maintainer directly.

Can you please run `./scripts/cargo-for-all-lock-files.sh tree` and commit the result to get further in CI?

**Review by CriesofCarrots — APPROVED** [review]

**Pull request merged**
