### PR TITLE
SVM: add `program_loader` module

### PR DESCRIPTION
**Pull request by buffalojoec**
#### Problem

The SVM's transaction processor - the entrypoint to the SVM - is becoming quite 
overloaded with functionality to handle processing transactions and loading 
accounts & programs.

The transaction processor should be the main entrypoint function, and it should 
call into other modules to handle isolated work as part of the transaction 
processing flow.

One such isolated responsibility is the loading of on-chain programs.

#### Summary of Changes

Create the `program_loader` module to mimick the `account_loader` module in 
loading programs - both from accounts and from bytes.

Drive the new `program_loader` from the main SVM transaction processor.

### CODE REVIEW

**Comment by buffalojoec** [comment]
@Lichtso this is the rest of #616, but depends on #1013.

**Review by dmakarov — COMMENTED** [review]
LGTM, but it seems spec.md needs to be updated accordingly.

**Comment by buffalojoec** [comment]
> LGTM, but it seems spec.md needs to be updated accordingly.

Sounds good, I'll make this update.

**Comment by pgarg66** [comment]
Were there any changes made to the functions that are moved to the new module? It's hard to tell by looking at the PR, and GH review doesn't help with such kind of code move.
Good cleanup overall!

**Comment by buffalojoec** [comment]
> Were there any changes made to the functions that are moved to the new module? It's hard to tell by looking at the PR, and GH review doesn't help with such kind of code move. Good cleanup overall!

Yes, there was one function that was taking `&self` but wasn't using it, and there was another that I added a few parameters. I think maybe I can re-write some of this commit history to make it easier to see those changes, but they are very minor. I'll do this!

**Comment by buffalojoec** [comment]
@pgarg66 this commit re-write should make the changes much more readable!

@dmakarov I've added a commit to update the spec!

**Review by LucasSte — APPROVED** [review]

**Review by pgarg66 — APPROVED** [review]

**Pull request merged**
