### PR TITLE
Fix setting an account override for fee payer

### LINKED ISSUE #2210: TransactionBatchProcessor::load_and_execute_sanitized_transactions does not look at account_overrides when doing fee checks
#### Problem
Doing ye old jito-solana rebase. Noticed some of the fee check logic has changed with SVM crate and account overrides aren't checked in TransactionBatchProcessor::validate_fees.

#### Proposed Solution
Add account overrides to TransactionBatchProcessor::validate_fees, use similar account loading logic there (load from cache first, then accountsdb)

### PR DESCRIPTION
**Pull request by ceciEstErmat**
Fixes #2210

Adding account override to validate_fee as to keep track to the fee payer state.
Added test to validate the change.

### CODE REVIEW

**Review by jstarry — DISMISSED** [review]

**Comment by ceciEstErmat** [comment]
Oupsi - didn't see the local-ci thingy. Running that and fixing everything.
Will push the fix once done :)

**Comment by ceciEstErmat** [comment]
@jstarry So I ran `ci/stable/run-localnet.sh` locally and it exited with zero which seems to indicate it ran well. Unsure tho :D

I see in the contributing.md it says - unsure if it's still true : 
```
Consider opening all PRs as Draft Pull Requests first. Using a draft PR allows
you to kickstart the CI automation, which typically takes between 10 and 30
minutes to execute.
```

Should i update my PR in consequence ?

**Comment by jstarry** [comment]
No need to update

**Comment by yihau** [comment]
maybe need a small change for fmt 🫠 

Screenshot 2024-08-05 at 22 21 54

**Comment by ceciEstErmat** [comment]
i'm actually unsure what happened here : 
https://buildkite.com/anza/agave/builds/8867#019122ff-4771-4806-99b8-520ba8f3813b
```
_bk;t=1722869817425[90m$[0m ci/docker-run-default-image.sh ci/test-docs.sh
_bk;t=1722869817432ci/docker-run-default-image.sh: Note: ignoring unknown argument: ci/test-docs.sh

_bk;t=1722869817436/var/lib/buildkite-agent/builds/ci19/anza/agave/ci/docker-run.sh: line 35: docker: command not found

_bk;t=1722869817437^^^ +++
_bk;t=1722869817437[31m🚨 Error: The command exited with status 127
```

**Comment by ceciEstErmat** [comment]
Unless i'm mistaken seems like everything is good ? First time contributing so idk if there is something else i should do :)

**Review by jstarry — APPROVED** [review]

**Comment by jstarry** [comment]
Thanks for your contribution @ceciEstErmat!

**Pull request merged**
