### PR TITLE
Add Option's commonly used methods to OptionSerializer

### PR DESCRIPTION
**Pull request by palinko91**
#### Problem
The OptionSerializer enum is not as easy to use ad the std::Option because many commonly used functions not implemented to it. For example if we are getting a JsonParsed transaction, to unwrap the meta, pre token balances etc we have to do it by hand. Also can't write if statements to only proceed if the OptionSerializer is Some. Adding these common methods can make it easier and more usual way to handle this type as we used to handle an Option.

#### Summary of Changes
Adding the most commonly used std::Option methods to OptionSerializer.

Fixes #
Missing functions added.

### CODE REVIEW

**Comment by palinko91** [comment]
Okay I'm not sure why committed all the 130 other commits again. I think better if I'm stop trying to fix it before I'm creating more mess :( Can I get some assistance what I'm doing the wrong way?

**Comment by CriesofCarrots** [comment]
Try:
```
git pull --rebase <upstream> master
```
where `<upstream>` is the `anza-xyz/agave:master` remote. Then you'll need to force-push to your branch

**Comment by palinko91** [comment]
> Try:
> 
> ```
> git pull --rebase <upstream> master
> ```
> 
> where `<upstream>` is the `anza-xyz/agave:master` remote. Then you'll need to force-push to your branch

I've tried this, got many conflicts, so basically I just continued with:
```
git checkout --theirs .
git add .
git rebase --continue
```

Until the rebase done, had to do few times. Unfortunatelly this pull request looks still so bad. Should I close it again and try to reopen to make it look more clean? Waiting for istructions.

Most likely the orginal problem is that I forked from Solana Labs which is behind, maybe it would be better if I'm deleting everything, forking from agave, applying the changes and asking PR.

**Comment by CriesofCarrots** [comment]
> Should I close it again and try to reopen to make it look more clean? Waiting for istructions.

Up to you whether you open a new PR or force push to this one, but it certainly can't be reviewed as is.
There are a few different ways to accomplish what you need to do, but without knowing your experience with git, I can't really advise you much further. Just know you need your branch to be synced with the tip of `anza-xyz/agave:master` with just your new commits on top.

It shouldn't be a problem that your fork is from solana-labs/solana; `solana-labs/solana:master` is a subset of `anza-xyz/agave:master`, so the difference should be a simple pull from the new remote.

**Comment by palinko91** [comment]
> > Should I close it again and try to reopen to make it look more clean? Waiting for istructions.
> 
> Up to you whether you open a new PR or force push to this one, but it certainly can't be reviewed as is. There are a few different ways to accomplish what you need to do, but without knowing your experience with git, I can't really advise you much further. Just know you need your branch to be synced with the tip of `anza-xyz/agave:master` with just your new commits on top.
> 
> It shouldn't be a problem that your fork is from solana-labs/solana; `solana-labs/solana:master` is a subset of `anza-xyz/agave:master`, so the difference should be a simple pull from the new remote.

I don't have too much experience with git, usually just using for my own repos and no one else committing there. So I'm using basic commands usually. I tried the rebase and the force push but as we can see not helped with too much things.

**Comment by palinko91** [comment]
Okay seems like I've solved. I've used interactive rebase and dropped the extra commits :)

**Review by CriesofCarrots — APPROVED** [review]
Thanks

**Pull request merged**
