### PR TITLE
ci: move benchmark to Github Action

### PR DESCRIPTION
**Pull request by yihau**
#### Problem

get some feedback from the previous PR: https://github.com/anza-xyz/agave/pull/2064

so now we decide to store datapoint into influxdb and show it on grafana

here is the page: https://metrics.solana.com:3000/d/aa57f0fe-b1e4-4600-937c-d840b466d19f/benchmark---agave

Screenshot 2024-07-29 at 22 35 35

#### Summary of Changes

- move benchmark to Gtihub Actions and the benchmark will only run when push to master atm

(the data will only keep 14days atm)

---

before merge

- [x] set up self-hosted runner
- [x] clean db

### CODE REVIEW

**Review by brooksprumo — COMMENTED** [review]
In the screenshots and the demo dashboard, I don't see results from the accounts-db benches. Are they being run, just not displayed? I assume yes, but wanted to double check.

Edit: Oh, I see now. On the dashboard you can select the accounts-db test suite.

**Comment by brooksprumo** [comment]
For the accounts-db tests, many use criterion to bench multiple different parameters per bench "name". On the accounts-db dashboard it looks like only a single parameter is shown per bench. Is that an issue with the dashboard, or is is that the output of the bench, the json, only have a single parameter?

**Comment by yihau** [comment]
> In the screenshots and the demo dashboard, I don't see results from the accounts-db benches. Are they being run, just not displayed? I assume yes, but wanted to double check.

> Edit: Oh, I see now. On the dashboard you can select the accounts-db test suite.

yeah, it looks a little bit confusing when we first enter. I added a friendly README!

Screenshot 2024-07-23 at 22 17 07

> For the accounts-db tests, many use criterion to bench multiple different parameters per bench "name". On the accounts-db dashboard it looks like only a single parameter is shown per bench. Is that an issue with the dashboard, or is is that the output of the bench, the json, only have a single parameter?

let me check this one 🫡

**Comment by bw-solana** [comment]
Looks really great!

**Comment by pgarg66** [comment]
Really cool. Love it!

**Comment by yihau** [comment]
added tables for the dashboard. it looks like this one now:

Screenshot 2024-07-24 at 23 20 28

**Comment by yihau** [comment]
@brooksprumo sorry for missing those tests. I figured out how to handle them. (normal bench and criterion bench) could you help me to check them again 🫠 

only 1 data for each tests because only the latest commit could generate/store them correctly 🙈 

Screenshot 2024-07-24 at 23 22 41

**Comment by brooksprumo** [comment]
> could you help me to check them again

Oooh, this is nice! This looks good to me!

**Comment by brooksprumo** [comment]
@yihau FYI, I just changed the name of one of the accounts-db benchmarks in https://github.com/anza-xyz/agave/pull/2261.

bench_hash_account used to have "data_size" then the number, now it has "blake3" and "lattice" then the number. Thanks in advance!

**Comment by HaoranYi** [comment]
This is so cool. Now we can track benchmark performance degradation! 👍

**Comment by yihau** [comment]
@brooksprumo thank you for the information! they looked good!

Screenshot 2024-07-25 at 23 59 23

**Review by brooksprumo — APPROVED** [review]
:shipit:

**Comment by ksolana** [comment]
Anything preventing this merge? Seems like a great feature to have it soon.

**Review by ksolana — APPROVED** [review]

**Review by bw-solana — APPROVED** [review]

**Pull request merged**
