### PR TITLE
Upgrades rust stable toolchain to 1.80.0

### PR DESCRIPTION
**Pull request by brooksprumo**
Rust 1.80.0 has been released.
https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html

### CODE REVIEW

**Comment by brooksprumo** [comment]
There's a lot of new warnings, but the overwhelming majority are these two, which are both about unexpected `cfg`s:

```
warning: unexpected `cfg` condition value: `solana`
 --> sdk/program-memory/src/lib.rs:6:7
  |
6 | #[cfg(target_os = "solana")]
  |       ^^^^^^^^^^^^^^^^^^^^
  |
  = note: expected values for `target_os` are: `aix`, `android`, `cuda`, `dragonfly`, `emscripten`, `espidf`, `freebsd`, `fuchsia`, `haiku`, `hermit`, `horizon`, `hurd`, `illumos`, `ios`, `l4re`, `linux`, `macos`, `netbsd`, `none`, `nto`, `openbsd`, `psp`, `redox`, `solaris`, `solid_asp3`, `teeos`, `tvos`, `uefi`, `unknown`, `visionos`, `vita`, `vxworks`, `wasi`, `watchos`, and `windows` and 2 more
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
```

and

```
warning: unexpected `cfg` condition name: `RUSTC_WITH_SPECIALIZATION`
 --> short-vec/src/lib.rs:2:13
  |
2 | #![cfg_attr(RUSTC_WITH_SPECIALIZATION, feature(min_specialization))]
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, and `windows`
  = help: consider using a Cargo feature instead
  = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
           [lints.rust]
           unexpected_cfgs = { level = "warn", check-cfg = ['cfg(RUSTC_WITH_SPECIALIZATION)'] }
  = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(RUSTC_WITH_SPECIALIZATION)");` to the top of the `build.rs`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
```

These lints will need to be resolved before upgrading will succeed.

Here's the full log when running the new clippy: 
[clippy-rust-1.80.0.log](https://github.com/user-attachments/files/16457087/clippy-rust-1.80.0.log)

**Comment by brooksprumo** [comment]
@yihau FYI

**Comment by brooksprumo** [comment]
To fix the "unexpected cfgs" lint:

Add this to the workspace Cargo.toml file:
```toml
[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))', 'cfg(RUSTC_WITH_SPECIALIZATION)'] }
```

And add this to all the package Cargo.toml files:
```toml
[lints]
workspace = true
```

References:
* https://blog.rust-lang.org/2024/05/06/check-cfg.html#expecting-custom-cfgs
* https://doc.rust-lang.org/cargo/reference/workspaces.html#the-lints-table
* https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-lints-section

**Comment by yihau** [comment]
uploaded the docker image but got the cfg warning in this PR. iirc our py script will complain about this new lint field

**Comment by brooksprumo** [comment]
> uploaded the docker image but got the cfg warning in this PR. iirc our py script will complain about this new lint field

Yep yep. Can your team pick up this PR to get the rust version upgraded? There are other lints to fix as well. Lots were related to docs formatting. Maybe there are others that actually touch code too.

**Comment by yihau** [comment]
okay. I think I will take over this one!

**Pull request closed without merging**
