### PR TITLE
[big-num-exp] Add bench code for big number modular exponentiation

### PR DESCRIPTION
**Pull request by samkim-crypto**
#### Problem
There is currently no bench code for the big number modular exponentiation syscalls.

#### Summary of Changes
Added bench for big number modular exponentiation.

I first created tests for exponents `3` and `65537`, which are common RSA exponents. For small numbers like these, the even modulus actually seems to perform better because it does not need montgomery translation.

For general exponents that are 512 bits and larger, even moduli seems to take longer than odd moduli as montgomery arithmetic starts to pay off.

Here is the result after running the benches on my dev machine.

```
test bench_big_num_exponentiation_exp_0512_bits_mod_0512_bits_even ... bench:     258,890.58 ns/iter (+/- 3,121.75)
test bench_big_num_exponentiation_exp_0512_bits_mod_0512_bits_odd  ... bench:     118,745.18 ns/iter (+/- 525.76)
test bench_big_num_exponentiation_exp_0512_bits_mod_1024_bits_even ... bench:     709,721.40 ns/iter (+/- 2,393.32)
test bench_big_num_exponentiation_exp_0512_bits_mod_1024_bits_odd  ... bench:     402,862.10 ns/iter (+/- 9,588.85)
test bench_big_num_exponentiation_exp_0512_bits_mod_2048_bits_even ... bench:   2,215,550.80 ns/iter (+/- 2,447.48)
test bench_big_num_exponentiation_exp_0512_bits_mod_2048_bits_odd  ... bench:   1,509,185.80 ns/iter (+/- 1,209.82)
test bench_big_num_exponentiation_exp_0512_bits_mod_4096_bits_even ... bench:   7,445,209.60 ns/iter (+/- 5,569.38)
test bench_big_num_exponentiation_exp_0512_bits_mod_4096_bits_odd  ... bench:   5,922,409.10 ns/iter (+/- 3,826.23)
test bench_big_num_exponentiation_exp_1024_bits_mod_1024_bits_even ... bench:   1,450,581.10 ns/iter (+/- 9,480.73)
test bench_big_num_exponentiation_exp_1024_bits_mod_1024_bits_odd  ... bench:     796,320.50 ns/iter (+/- 1,113.82)
test bench_big_num_exponentiation_exp_1024_bits_mod_2048_bits_even ... bench:   4,431,258.20 ns/iter (+/- 4,881.54)
test bench_big_num_exponentiation_exp_1024_bits_mod_2048_bits_odd  ... bench:   2,987,158.20 ns/iter (+/- 2,998.16)
test bench_big_num_exponentiation_exp_1024_bits_mod_4096_bits_even ... bench:  14,938,423.10 ns/iter (+/- 7,876.93)
test bench_big_num_exponentiation_exp_1024_bits_mod_4096_bits_odd  ... bench:  11,719,912.60 ns/iter (+/- 11,669.47)
test bench_big_num_exponentiation_exp_2048_bits_mod_2048_bits_even ... bench:   8,807,631.70 ns/iter (+/- 8,775.75)
test bench_big_num_exponentiation_exp_2048_bits_mod_2048_bits_odd  ... bench:   5,940,002.30 ns/iter (+/- 3,673.43)
test bench_big_num_exponentiation_exp_2048_bits_mod_4096_bits_even ... bench:  29,631,355.20 ns/iter (+/- 229,227.14)
test bench_big_num_exponentiation_exp_2048_bits_mod_4096_bits_odd  ... bench:  23,321,553.60 ns/iter (+/- 50,072.37)
test bench_big_num_exponentiation_exp_3_mod_0512_bits_even         ... bench:         891.81 ns/iter (+/- 3.80)
test bench_big_num_exponentiation_exp_3_mod_0512_bits_odd          ... bench:      17,154.77 ns/iter (+/- 27.49)
test bench_big_num_exponentiation_exp_3_mod_1024_bits_even         ... bench:       2,171.01 ns/iter (+/- 30.25)
test bench_big_num_exponentiation_exp_3_mod_1024_bits_odd          ... bench:      58,377.91 ns/iter (+/- 67.25)
test bench_big_num_exponentiation_exp_3_mod_2048_bits_even         ... bench:       6,558.96 ns/iter (+/- 10.03)
test bench_big_num_exponentiation_exp_3_mod_2048_bits_odd          ... bench:     217,277.00 ns/iter (+/- 213.65)
test bench_big_num_exponentiation_exp_3_mod_4096_bits_even         ... bench:      20,968.88 ns/iter (+/- 36.13)
test bench_big_num_exponentiation_exp_3_mod_4096_bits_odd          ... bench:     849,335.00 ns/iter (+/- 639.38)
test bench_big_num_exponentiation_exp_4096_bits_mod_4096_bits_even ... bench:  60,570,213.80 ns/iter (+/- 333,536.81)
test bench_big_num_exponentiation_exp_4096_bits_mod_4096_bits_odd  ... bench:  46,523,714.50 ns/iter (+/- 245,274.18)
test bench_big_num_exponentiation_exp_65537_mod_0512_bits_even     ... bench:       5,810.86 ns/iter (+/- 86.79)
test bench_big_num_exponentiation_exp_65537_mod_0512_bits_odd      ... bench:      17,227.66 ns/iter (+/- 91.55)
test bench_big_num_exponentiation_exp_65537_mod_1024_bits_even     ... bench:      15,637.35 ns/iter (+/- 100.93)
test bench_big_num_exponentiation_exp_65537_mod_1024_bits_odd      ... bench:      58,491.36 ns/iter (+/- 53.03)
test bench_big_num_exponentiation_exp_65537_mod_2048_bits_even     ... bench:      50,390.28 ns/iter (+/- 52.07)
test bench_big_num_exponentiation_exp_65537_mod_2048_bits_odd      ... bench:     217,823.52 ns/iter (+/- 579.03)
test bench_big_num_exponentiation_exp_65537_mod_4096_bits_even     ... bench:     167,513.18 ns/iter (+/- 381.01)
test bench_big_num_exponentiation_exp_65537_mod_4096_bits_odd      ... bench:     849,666.60 ns/iter (+/- 789.10)
```

Fixes #

### CODE REVIEW

**Review by vadorovsky — APPROVED** [review]
Overall looks good.

I was thinking whether hard coding these big numbers could be avoided by using a seedable RNG, but I don't think there is an easy way to request generating odd or even numbers without writing some manual retry loops, so at the end it's probably not worth it.

**Review by joncinque — APPROVED** [review]
Looks good to me, but I can't comment on whether the chosen numbers are good :sweat_smile:

**Comment by 0x0ece** [comment]
Nice! I think this confirms that we should limit to 1) odd modulus, 2) small exponent.

**Comment by samkim-crypto** [comment]
> I was thinking whether hard coding these big numbers could be avoided by using a seedable RNG, but I don't think there is an easy way to request generating odd or even numbers without writing some manual retry loops, so at the end it's probably not worth it.

Yeah I considered that option as well, but I also thought that it will probably not worth it. Thanks for taking a look!

> Nice! I think this confirms that we should limit to 1) odd modulus, 2) small exponent.

Yep, for the modulus, if we are to target RSA applications, we should certainly target odd moduli. I am not sure yet how frequent bigger exponents are used (if at all) in authentication protocols, but I'll look into it. It seems reasonable to restrict to just small exponents initially though as you suggested.

**Pull request merged**
