### PR TITLE
Upgrade tikv-jemallocator to 0.6

### LINKED ISSUE #2395: Upgrade tikv-jemallocator to latest version .6.0
The current version is over three years old. And the latest one has some profiling tools that can be useful to get stats as we see memory pressure as become an issue recently (#2126).

https://github.com/tikv/jemallocator/blob/main/CHANGELOG.md#060---2024-07-14

### PR DESCRIPTION
**Pull request by ksolana**
Fixes: #2395

Dashboard: https://metrics.solana.com:8889/sources/27/dashboards/128?refresh=Paused&lower=now%28%29%20-%207d

### CODE REVIEW

**Comment by ksolana** [comment]
Related patches/issues
- https://github.com/anza-xyz/agave/pull/1250
- https://github.com/anza-xyz/agave/pull/1364
- https://github.com/solana-labs/solana/issues/27275
- https://github.com/anza-xyz/agave/pull/1370

**Comment by ksolana** [comment]
Results https://metrics.solana.com:8889/sources/27/chronograf/data-explorer?query=SELECT%20mean%28%22avail_percent%22%29%20AS%20%22mean_avail_percent%22%2C%20mean%28%22free_percent%22%29%20AS%20%22mean_free_percent%22%2C%20mean%28%22swap_free_percent%22%29%20AS%20%22mean_swap_free_percent%22%20FROM%20%22mainnet-beta%22.%22autogen%22.%22memory-stats%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20AND%20%22host_id%22%3D%27FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk%27%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29#

**Comment by ksolana** [comment]
Latest results in here:
https://metrics.solana.com:8889/sources/27/chronograf/data-explorer?query=SELECT%20mean%28%22free_percent%22%29%20AS%20%22mean_free_percent%22%20FROM%20%22mainnet-beta%22.%22autogen%22.%22memory-stats%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20AND%20%22host_id%22%3D%27FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk%27%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29#

**Comment by ksolana** [comment]
free_percent: "mean_free_percent" FROM "mainnet-beta"."autogen"."memory-stats"

Screenshot 2024-10-19 at 3 08 59 PM

**Comment by ksolana** [comment]
https://metrics.solana.com:8889/sources/27/chronograf/data-explorer?query=SELECT%20mean%28%22streamer-send-bytes_total%22%29%20AS%20%22mean_streamer-send-bytes_total%22%20FROM%20%22mainnet-beta%22.%22autogen%22.%22Gossip%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20AND%20%22host_id%22%3D%27FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk%27%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29

"mean_streamer-send-bytes_total" FROM "mainnet-beta"."autogen"."Gossip"

Screenshot 2024-10-19 at 3 46 49 PM

**Comment by ksolana** [comment]
https://metrics.solana.com:8889/sources/27/chronograf/data-explorer?query=SELECT%20mean%28%22avail_percent%22%29%20AS%20%22mean_avail_percent%22%20FROM%20%22mainnet-beta%22.%22autogen%22.%22memory-stats%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20AND%20%22host_id%22%3D%27FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk%27%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29

"mean_avail_percent" FROM "mainnet-beta"."autogen"."memory-stats"

Screenshot 2024-10-19 at 3 52 46 PM

**Comment by ksolana** [comment]
https://metrics.solana.com:8889/sources/27/chronograf/data-explorer?query=SELECT%20mean%28%22streamer-send-host_bytes_90pct%22%29%20AS%20%22mean_streamer-send-host_bytes_90pct%22%20FROM%20%22mainnet-beta%22.%22autogen%22.%22Gossip%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20AND%20%22host_id%22%3D%27FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk%27%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29

```sql
SELECT mean("streamer-send-host_bytes_90pct") AS "mean_streamer-send-host_bytes_90pct" FROM "mainnet-beta"."autogen"."Gossip" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "host_id"='FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk' GROUP BY time(:interval:) FILL(null)
```

Screenshot 2024-10-19 at 3 55 24 PM

**Comment by ksolana** [comment]
```sql
SELECT mean("streamer-send-bytes_total") AS "mean_streamer-send-bytes_total" FROM "mainnet-beta"."autogen"."Gossip" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "host_id"='FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk' GROUP BY time(:interval:) FILL(null)
```

https://metrics.solana.com:8889/sources/27/chronograf/data-explorer?query=SELECT%20mean%28%22streamer-send-bytes_total%22%29%20AS%20%22mean_streamer-send-bytes_total%22%20FROM%20%22mainnet-beta%22.%22autogen%22.%22Gossip%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20AND%20%22host_id%22%3D%27FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk%27%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29

Screenshot 2024-10-19 at 4 01 33 PM

**Comment by ksolana** [comment]
```sql
SELECT mean("buffers_percent") AS "mean_buffers_percent" FROM "mainnet-beta"."autogen"."memory-stats" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "host_id"='FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk' GROUP BY time(:interval:) FILL(null)
```
https://metrics.solana.com:8889/sources/27/chronograf/data-explorer?query=SELECT%20mean%28%22buffers_percent%22%29%20AS%20%22mean_buffers_percent%22%20FROM%20%22mainnet-beta%22.%22autogen%22.%22memory-stats%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20AND%20%22host_id%22%3D%27FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk%27%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29

Screenshot 2024-10-19 at 4 04 01 PM

**Comment by ksolana** [comment]
https://metrics.solana.com:8889/sources/27/chronograf/data-explorer?query=SELECT%20mean%28%22used_bytes%22%29%20AS%20%22mean_used_bytes%22%20FROM%20%22mainnet-beta%22.%22autogen%22.%22memory-stats%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20AND%20%22host_id%22%3D%27FW2Ynx5hx5yc4FM1buAfohgF7s2U6pcrC3DK7CfauThk%27%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29#

Screenshot 2024-10-29 at 10 24 34 PM

**Review by alessandrod — APPROVED** [review]

**Pull request merged**
