### PR TITLE
Add multithreaded test infrastructure with Shuttle

### PR DESCRIPTION
**Pull request by LucasSte**
#### Problem

The program cache has multiple synchronization mechanisms without any systemic test infrastructure. Although PR #1471 introduced an adhoc test for program cache, it is insufficient for finding issues in the code.

#### Summary of Changes

I want to adopt [shuttle](https://github.com/awslabs/shuttle) to run specialized multithreaded test in the CI. In order for it to work, all `sync`, `rand` and `thread` imports must come from `shuttle`.

### CODE REVIEW

**Comment by alessandrod** [comment]
instead of `cfg`ing shuttle everywhere, we could have an internal `thread` module somewhere that imports the OG stuff or shuttle depending on cfg.

**Comment by LucasSte** [comment]
> instead of `cfg`ing shuttle everywhere, we could have an internal `thread` module somewhere that imports the OG stuff or shuttle depending on cfg.

Do you mean another create in the monorepo? I need the shuttle imports across multiple crates, so a module in one of the existing ones wouldn't work I guess.

**Comment by alessandrod** [comment]
> > instead of `cfg`ing shuttle everywhere, we could have an internal `thread` module somewhere that imports the OG stuff or shuttle depending on cfg.
> 
> Do you mean another create in the monorepo? I need the shuttle imports across multiple crates, so a module in one of the existing ones wouldn't work I guess.

Hmm, with some luck there's a crate that is imported by pretty much everything? sdk? :D

**Comment by LucasSte** [comment]
> > > instead of `cfg`ing shuttle everywhere, we could have an internal `thread` module somewhere that imports the OG stuff or shuttle depending on cfg.
> > 
> > 
> > Do you mean another create in the monorepo? I need the shuttle imports across multiple crates, so a module in one of the existing ones wouldn't work I guess.
> 
> Hmm, with some luck there's a crate that is imported by pretty much everything? sdk? :D

That would surely work, but enforcing people to use the right import would be difficult.

**Comment by alessandrod** [comment]
> > > > instead of `cfg`ing shuttle everywhere, we could have an internal `thread` module somewhere that imports the OG stuff or shuttle depending on cfg.
> > > 
> > > 
> > > Do you mean another create in the monorepo? I need the shuttle imports across multiple crates, so a module in one of the existing ones wouldn't work I guess.
> > 
> > 
> > Hmm, with some luck there's a crate that is imported by pretty much everything? sdk? :D
> 
> That would surely work, but enforcing people to use the right import would be difficult.

wouldn't be more difficult than making them import shuttle?

**Comment by LucasSte** [comment]
> > > > > instead of `cfg`ing shuttle everywhere, we could have an internal `thread` module somewhere that imports the OG stuff or shuttle depending on cfg.
> > > > 
> > > > 
> > > > Do you mean another create in the monorepo? I need the shuttle imports across multiple crates, so a module in one of the existing ones wouldn't work I guess.
> > > 
> > > 
> > > Hmm, with some luck there's a crate that is imported by pretty much everything? sdk? :D
> > 
> > 
> > That would surely work, but enforcing people to use the right import would be difficult.
> 
> wouldn't be more difficult than making them import shuttle?

Fair point. There are drawbacks in both approaches. On one hand, people may forget to add the shuttle import, on the other, they may still import from `std::sync`, instead of `solana_sdk::sync` (for example).

**Comment by LucasSte** [comment]
I'm open to changing then. Anyone else wants to weight in? @Lichtso and @pgarg66 ?

**Comment by LucasSte** [comment]
Closing this PR in favor of #1634.

**Pull request closed without merging**
