### PR TITLE
move metrics usage out of program-runtime

### PR DESCRIPTION
**Pull request by kevinheavey**
#### Problem
solana-program-runtime has an annoying solana-metrics dependency that severely impacts build time and dependency hell. It's particularly annoying for litesvm which depends on solana-program-runtime

#### Summary of Changes
- Make a new solana-program-runtime-metrics crate
- Move LoadProgramMetrics into the new crate
- Move ProgramCacheEntry::new and ProgramCacheEntry::reload into the new crate as free functions
- Update all affected usage of program-runtime in this repo to use the new crate where necessary

None of these API changes affect crates that are covered by the backwards compatibility policy. I don't think deprecation is the way to go here as it would require waiting a long time to actually remove the dependencies

### CODE REVIEW

**Review by buffalojoec — COMMENTED** [review]
I don't think this is the best way to go about removing the metrics dependency from the program-runtime.

This adds unnecessary indirection to the program cache API, calling into free functions in some other crate. Additionally, the intention here is to make a program-runtime _metrics_ crate, but that's not what the crate proposed here does. It has a lot of the same dependencies as the program-runtime and shares ELF-loading responsibilities with the main program-runtime crate. Metrics are still a side job.

I wonder if we can just put the metrics struct, the datapoint submissions, and the argument for `&mut LoadProgramMetrics` behind a `metrics` feature flag. This way, LiteSVM can just use program-runtime without the `metrics` feature.

**Comment by kevinheavey** [comment]
Something like this? https://github.com/anza-xyz/agave/pull/3477

**Comment by buffalojoec** [comment]
> Something like this? #3477

Yes. Does that approach solve your problem in LiteSVM?

**Comment by kevinheavey** [comment]
> Yes. Does that approach solve your problem in LiteSVM?

Not without #3383

**Comment by kevinheavey** [comment]
Closing in favour of #3477

**Pull request closed without merging**
