### PR TITLE
debug logging 

### PR DESCRIPTION
**Pull request by fkouteib**
DO NOT MERGE.

throwaway debug code.

### CODE REVIEW

**Comment by fkouteib** [comment]
@bw-solana this is ready for review.

@joeaba Pending Brennan's sign-off, this is the code we would want to deploy for today's long ping issue. thanks.

**Comment by bw-solana** [comment]
LGTM

**Comment by fkouteib** [comment]
I will do more local testing on this tomorrow (6/26). Please hold off on kicking off the next step.

**Comment by fkouteib** [comment]
updated to target v1.18.18.

**Pull request closed without merging**
