### PR TITLE
 accounts db/refactor accounts db test - fix account storage count and alive bytes tests for hot storage

### PR DESCRIPTION
**Pull request by HaoranYi**
#### Problem

Add tests coverage for storage count and alive bytes tests for hot storage.

Continued on #777

#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by HaoranYi** [comment]
The actual change is in the last commit. 
Please only review the last change if you have already reviewed #777

**Review by brooksprumo — COMMENTED** [review]
Looks good to me. Please re-request a review once #777 has been merged and this PR is rebased.

**Comment by HaoranYi** [comment]
No code changes. Rebased on master to pickup #777
@brooksprumo @jeffwashington Please review it again. Thanks!

**Review by brooksprumo — APPROVED** [review]
:shipit:

**Review by jeffwashington — APPROVED** [review]
lgtm. thanks!

**Pull request merged**
