### PR TITLE
Back-port Bump platform tools version (from `solana-labs/solana` #35330)

### PR DESCRIPTION
**Pull request by LucasSte**
#### Problem

Platform tools v1.39 shipped with Solana v1.18 contains a bug in the discriminator size and in the stack allocation.

The new version contains a fix for the incorrect enum size introduced in Rust 1.72: https://github.com/anza-xyz/rust/pull/90. This could cause programs to stop working, if developers build them with new tools.

In addition, v1.39 introduced changes in the SROA (Scalar Replacement of Aggregates) pass, which caused multiple functions to utilize more stack space than before: #252. v1.41 fixes this as well.

#### Summary of Changes

This is a back port of https://github.com/solana-labs/solana/pull/35330 to v1.18.

### CODE REVIEW

**Review by willhickey — APPROVED** [review]
Approved for v1.18, pending review from someone familiar with this part of the code and CI passing

We're manually syncing all changes back to `solana-labs/solana` so we can create parallel releases. Can the two `anza-xyz/platform-tools` references here be left as `solana-labs/platform-tools` in the `solana-labs/solana` version of this change?

It looks like both copies of the platform-tools repo have `a198faafa9c75f13935322f0293f24a2c3ea4b90` as `1.41`.

**Comment by LucasSte** [comment]
> Approved for v1.18, pending review from someone familiar with this part of the code and CI passing

@willhickey `cargo-audit` in the CI is pointing a vulnerability in crate mio. I tested the command locally without my changes and the error persists. Should we update this in v1.18 as well?

> We're manually syncing all changes back to `solana-labs/solana` so we can create parallel releases. Can the two `anza-xyz/platform-tools` references here be left as `solana-labs/platform-tools` in the `solana-labs/solana` version of this change?
> 
> It looks like both copies of the platform-tools repo have `a198faafa9c75f13935322f0293f24a2c3ea4b90` as `1.41`.

The `platform-tools` repository has moved to Anza. If the change in references does not brake the links, renaming should be fine.

**Review by dmakarov — APPROVED** [review]

**Comment by LucasSte** [comment]
> > Approved for v1.18, pending review from someone familiar with this part of the code and CI passing
> 
> @willhickey `cargo-audit` in the CI is pointing a vulnerability in crate mio. I tested the command locally without my changes and the error persists. Should we update this in v1.18 as well?

It looks like merging with the latest v1.18 version has fixed the issue.

**Comment by CriesofCarrots** [comment]
@LucasSte , in future, please rebase and force push instead of the merge commit

**Pull request merged**
