### PR TITLE
Health check slot distance

### PR DESCRIPTION
**Pull request by bartenbach**
#### Problem
Default health check size is arbitrary and inconsistent with delinquency constant.

#### Summary of Changes
Changes arbitrary health check slot distance to delinquency constant.

### CODE REVIEW

**Review by steviez — DISMISSED** [review]
This looks good to me, thanks for raising / making the PR!

It looks like `128` originates from here:
https://github.com/solana-labs/solana/commit/8e2745c2a24

and `150` from here:
https://github.com/solana-labs/solana/commit/40737e9efa4

@CriesofCarrots - Do you have any reservations about this change? Technically, I think `150` pre-dates `128`, but `128` is in a more visible place and a power-of-2 😉 .

Technically, this will make the healthy/not-healthy bound a little stricter for validators, but `128` is still pretty gratuitous. I'm inclined to think that the use of different values was just a minor oversight

**Comment by bartenbach** [comment]
As a validator (speaking just for myself), I would prefer the stricter health check that is in line with the definition of delinquency.

It makes sense that you would want to make sure your validator was not delinquent to be considered "healthy". 150 gets you close, but I can't think of any reason for the extra grace in this circumstance.

**Review by CriesofCarrots — DISMISSED** [review]
> @CriesofCarrots - Do you have any reservations about this change? Technically, I think 150 pre-dates 128, but 128 is in a more visible place and a power-of-2 😉 .

Given that the value is still configurable, I don't have any reservations. Might be worth mentioning in the changelog, though.

**Comment by steviez** [comment]
Ohh yeah, good call on changelog. @bartenbach, can you please make an addition there as well:
https://github.com/anza-xyz/agave/blob/master/CHANGELOG.md

Something like:
> Change default value for --health-check-slot-distance from 150 to 128

I don't anticipate us BP'ing this change, so I think under the `2.0.0` section is appropriate

**Review by steviez — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
