### PR TITLE
v2.1: ignore rustls rustsec

### PR DESCRIPTION
**Pull request by yihau**
#### Summary of Changes

ignore rustls rustsec

Close #3791

### CODE REVIEW

**Review by willhickey — APPROVED** [review]

**Comment by bw-solana** [comment]
We don't use any of the exposed APIs, so this should be fine. Can update the crate on master

**Review by bw-solana — APPROVED** [review]

**Comment by willhickey** [comment]
> Can update the crate on master

Chido updated master yesterday https://github.com/anza-xyz/agave/pull/3772

v2.0 uses an unaffected version, so we're good once this is merged

**Comment by brooksprumo** [comment]
Looks like CI is busted due to the platform tools update?

**Comment by bw-solana** [comment]
> Looks like CI is busted due to the platform tools update?

Need this one I believe: https://github.com/anza-xyz/agave/pull/3774

**Comment by willhickey** [comment]
I have cherry-picked this change onto https://github.com/anza-xyz/agave/pull/3777

If CI passes cleanly there I will briefly enable rebase & merge and merge #3777 (so we get distinct commits on v2.1) and close this one.

**Comment by yihau** [comment]
use #3777

**Pull request closed without merging**
