### PR TITLE
Use rand::seq::index::sample_weighted for weighted_random_order_by_stake

### PR DESCRIPTION
**Pull request by ksolana**
Now that rand>=0.8 is being used.

### CODE REVIEW

**Comment by AshwinSekar** [comment]
`rand::seq::index::sample_weighted` provides the same functionality when `length == amount`. 
you can find the source here https://rust-random.github.io/rand/src/rand/seq/index.rs.html#349 which is what this function is modelled after.

**Comment by ksolana** [comment]
> `rand::seq::index::sample_weighted` provides the same functionality when `length == amount`. you can find the source here https://rust-random.github.io/rand/src/rand/seq/index.rs.html#349 which is what this function is modelled after.

I see. Updated the patch using sample_weighted

**Comment by illia-bobyr** [comment]
> `rand::seq::index::sample_weighted` provides the same functionality when `length == amount`. you can find the source here [rust-random.github.io/rand/src/rand/seq/index.rs.html](https://rust-random.github.io/rand/src/rand/seq/index.rs.html#349) which is what this function is modelled after.

There is a difference, it does not sort the returned vector: https://rust-random.github.io/rand/src/rand/seq/index.rs.html#414-425
One location where `weighted_random_order_by_stake` is used is where we are sending votes.
It seems like we want to send them in the most staked order first?

Otherwise, it is just a randomization, and there is no reason to assign weights at all.

**Comment by AshwinSekar** [comment]
ah very nice catch, didn't notice that it was not sorted by weight.
In this case I believe it is fine to use the current implementation or even the firedancer port https://github.com/anza-xyz/agave/blob/master/gossip/src/weighted_shuffle.rs#L207, although that might be overkill for the < 3k pubkeys we have right now.

**Comment by ksolana** [comment]
Yeah and because the weights aren't returned, there is no way to sort them on the caller's side. Abandoning it.

**Pull request closed without merging**
