### PR TITLE
fix: solana downloads should default to stable release

### PR DESCRIPTION
**Pull request by mikemaccana**
#### Problem

Multiple developers have had problems installing the Solana CLI because software requiring Solana is currently built against `stable` and https://docs.solanalabs.com/cli/install points to beta. 

#### Summary of Changes

Sets the default version for download to be stable version, using the same method (CI) as previously. Do not ever default to beta, even if BETA_CHANNEL_LATEST_TAG is set.

### CODE REVIEW

**Comment by jacobcreech** [comment]
@mikemaccana I don't think this is correct. Rather, I think something else is wrong.

While stable should have `stable` as the installation, edge and beta should still be input when it is on edge and beta. That's how https://beta.docs.solanalabs.com/cli/install and https://edge.docs.solanalabs.com/cli/install get updated. However, looks like they're out of date/broken too. There's something else wrong.

**Comment by mikemaccana** [comment]
@jacobcreech "edge and beta should still be input when it is on edge and beta. "

This sentence isn't clear. What does 'it is on edge and beta' mean? If 'it' refers to to the Solana CLI, what does the Solana CLI being on edge and beta mean? If 'it' refers to something else, what is 'it'?

If you means that someone following the existing instructions to use a release tag:

> You can replace v1.18.4 with the release tag matching the software version of your desired release, or use one of the three symbolic channel names: stable, beta, or edge.

Will be affected, they won't be, as far as I can tell.

**Comment by steviez** [comment]
> What does 'it is on edge and beta' mean?

https://github.com/anza-xyz/agave/blob/master/RELEASE.md

**Comment by mikemaccana** [comment]
@steviez I was already aware Agave has has an edge and beta branch, I read the document anyway in case something unexpected appeared, but I still have the same question: what is 'it'? The CLI itself cannot be on edge or beta releases as I understand it, it simply has edge or beta releases. Which users can still install if they want.

I'll try and simplify. Quoting the current page:

> Install the Solana release [v1.18.4](https://github.com/solana-labs/solana/releases/tag/v1.18.4) on your machine by running:
>
> sh -c "$(curl -sSfL https://release.solana.com/v1.18.4/install)"
>
> You can replace v1.18.4 with the release tag matching the software version of your desired release, or use one of the three symbolic channel names: stable, beta, or edge.

The problem:

 - The default should be whatever branch is stable
 - The default should not be beta
 
**Please let me know if that is not accurate.**

This PR will have the following affects:

 - Make stable the default
 - People that wish to explicitly download and install beta or edge still have the ability to download and install beta by using the channel name of beta and edge or putting in an explicit release number.
 
**Please let me know if that is not accurate.**

Thanks! My feeling is that is a very simple issue made to seem complex by the vagaries of text communication.

**Comment by mikemaccana** [comment]
I'll try and simplify.


```
Install the Solana release [v1.18.4](https://github.com/solana-labs/solana/releases/tag/v1.18.4) on your machine by running:

sh -c "$(curl -sSfL https://release.solana.com/v1.18.4/install)"

You can replace v1.18.4 with the release tag matching the software version of your desired release, or use one of the three symbolic channel names: stable, beta, or edge.
```

The problem:

 - The default should be whatever branch is stable
 - The default should not be beta
 
**Please let me know if that is not accurate.**

This PR will have the following affects:

 - Make stable the default
 - People that wish to explicitly download and install beta or edge still have the ability to download and install beta by using the channel name of beta and edge or putting in an explicit release number.
 
**Please let me know if that is not accurate.**

**Comment by jacobcreech** [comment]
> what is 'it'

it = docs in this context.

When docs are deployed on edge.docs.solana.com or beta.docs.solanalabs.com, the CLI installation instructions for each should say the subsequent edge or stable version. "Stable", or docs.solanalabs.com, should say to install the stable version. As we can see from the live version set at docs.solanalabs.com, the command is shown to install 1.18.4, `sh -c "$(curl -sSfL https://release.solana.com/v1.18.4/install)"`, but this is not stable. 

From this we can understand that something is going wrong calculating this version. We want to avoid setting a single version for all different deployments of docs because the CLI reference material is generated based on the version specified.

**Comment by mikemaccana** [comment]
Closing this as it seems more work is needed due to the separate instances of the docs site, in favor of the issue filed above.

**Pull request closed without merging**
