### PR TITLE
remove respan macro

### PR DESCRIPTION
**Pull request by kevinheavey**
This isn't used anywhere in this repo or solana-program-library, and I can't imagine it's used anywhere else. Thoughts?

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
I think this is fine, but I want to do a little more research before moving forward with this.

**Comment by kevinheavey** [comment]
I ran a search for `respan!` on Sourcegraph and nothing came up that uses it (there are some old Solana forks that use `respan` in the sense that the forks contain their own definition of `respan` and the old Solana code that used `respan`) https://sourcegraph.com/search?q=context%3Aglobal+respan%21&patternType=keyword&sm=0&filters=%5B%5B%22lang%22%2C%22Rust%22%2C%22lang%3Arust%22%5D%5D

**Comment by kevinheavey** [comment]
Oh another point is that the doc comment says "For internal use only."

**Review by CriesofCarrots — COMMENTED** [review]
Thanks for your patience while I traced the repo history of this (and got sidetracked by other things), and thanks for the legwork.
I am now on board with this removal.

Could you please add a line to CHANGELOG.md? Then lgtm

**Review by CriesofCarrots — APPROVED** [review]

**Pull request merged**
