### PR TITLE
Extract commitment-config crate

### PR DESCRIPTION
**Pull request by kevinheavey**
#### Problem
`solana_sdk::commitment_config` imposes a `solana_sdk` dependency on `solana_rpc_client`

#### Summary of Changes
- move commitment_config.rs to its own crate
- make serde optional in the new crate
- re-export it in solana-sdk (with serde enabled)

### CODE REVIEW

**Comment by febo** [comment]
It seems that `CommitmentConfig` is always used in combination with `RpcClient` so I wonder whether they should be on the same crate or not. Not sure if there is a scenario where we would use `CommitmentConfig` and not the `RpcClient`.

**Comment by kevinheavey** [comment]
> It seems that `CommitmentConfig` is always used in combination with `RpcClient` so I wonder whether they should be on the same crate or not. Not sure if there is a scenario where we would use `CommitmentConfig` and not the `RpcClient`.

It's also used in the Client and AsyncClient traits in `solana_sdk::client`, and in solana-banks-client

**Comment by febo** [comment]
> > It seems that `CommitmentConfig` is always used in combination with `RpcClient` so I wonder whether they should be on the same crate or not. Not sure if there is a scenario where we would use `CommitmentConfig` and not the `RpcClient`.
> 
> It's also used in the Client and AsyncClient traits in `solana_sdk::client`, and in solana-banks-client

Not sure why my search did not return those uses but I can see them there. 😅

**Review by febo — COMMENTED** [review]
Looks good - just waiting for the crate + CI to pass before approving.

cc: @yihau

**Comment by yihau** [comment]
✅

**Review by febo — APPROVED** [review]

**Pull request merged**
