### PR TITLE
ancient packing iterates serially instead of parallel

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem
With `par_iter`, there is no guarantee of execution order.
If account a is dead in slot 1 and alive with zero lamports in slot 2, then if `par_iter` visits slot 1 first, it will unrefs account a in the index since slot 1 will be rewritten to not include the dead account a in slot 1.
Then, when slot 2 is visited, account a will report a refcount of 1. This means it could be deleted since it is a zero lamport account with only a single refcount. However, if we later fail to pack slot 1 (due to multirefs or something), then we addref account a. But, at that point, we've already treated account a in slot 2 as a single ref count zero lamport account as opposed to a multi ref alive account. We would then delete account a from slot 2, remove the slot list for account a, and decrement the refcount. This results in account a in the index (or maybe even not!) with a slot list that is empty and a refcount of 1. This means next time we run a hash of all accounts, we will find the older, 'dead' account. This produces the wrong cap and/or hash of all accounts.

#### Summary of Changes
Iterate slots in slot order highest to lowest. This allows us to correctly unref dead accounts and then reverse that decision without producing an indcorrect result.

Fixes #

### CODE REVIEW

**Review by brooksprumo — COMMENTED** [review]
Changes look good to me, as correctness is the highest priority. Do you have any perf numbers on how much this change actually impacts runtime for getting `accounts_to_combine`?

**Comment by jeffwashington** [comment]
> Changes look good to me, as correctness is the highest priority. Do you have any perf numbers on how much this change actually impacts runtime for getting `accounts_to_combine`?

Here's a ledger tool run from a mnb snapshot that runs long enough to pack twice.
Numbers are close enough. Read is faster now. Note that the read times are measured at the per-slot level. This is a bg process. Not sure how consistent the numbers are. I imagine there is a lot of variation.
There may be less contention on the index reading now than before.

```
this pr:
[2024-08-27T14:08:17.325449184Z INFO  solana_metrics::metrics] datapoint: shrink_ancient_stats num_slots_shrunk=7
index_read_elapsed=185,734
total_us=1,395,205
[2024-08-27T14:15:52.031799590Z INFO  solana_metrics::metrics] datapoint: shrink_ancient_stats num_slots_shrunk=7
index_read_elapsed=199,878
total_us=2,350,142

master:
[2024-08-27T14:29:08.649332096Z INFO  solana_metrics::metrics] datapoint: shrink_ancient_stats num_slots_shrunk=7
index_read_elapsed=324,871
total_us=1,277,048
[2024-08-27T14:36:39.865026033Z INFO  solana_metrics::metrics] datapoint: shrink_ancient_stats num_slots_shrunk=7
index_read_elapsed=555,725
total_us=1,990,582
```

**Review by HaoranYi — APPROVED** [review]
lgtm.

**Review by brooksprumo — APPROVED** [review]
:shipit: 

Nice, not much of a perf difference either.

**Pull request merged**
