### PR TITLE
rework account load with check_and_get_loaded_account_shared_data

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem
Accounts db is slow when mmaps exceed free ram.

#### Summary of Changes
use a new version of the api `check_and_get_loaded_account_shared_data` which makes it clear the caller directly wants `AccountSharedData`. This can be used to optimize the code in the storage that returns the account. This will use #508 once everything is all worked out.

Fixes #

### CODE REVIEW

**Review by HaoranYi — COMMENTED** [review]
The refactor looks correct to me. I assume that the existing tests have already covered the new `check_and_get_loaded_account_shared_data`.

**Comment by jeffwashington** [comment]
> The refactor looks correct to me. I assume that the existing tests have already covered the new `check_and_get_loaded_account_shared_data`.

i simplified this and went over the code coverage report. I will check out the new code coverage report.

**Review by brooksprumo — APPROVED** [review]
:shipit: 

Wow, I had to stare at this one for a long time... I think I've convinced myself I understand it, esp. when considering #508.

**Comment by jeffwashington** [comment]
> The refactor looks correct to me. I assume that the existing tests have already covered the new `check_and_get_loaded_account_shared_data`.

This is called everytime we load an account for tx processing. Testing is sufficient.

**Comment by HaoranYi** [comment]
lgtm

**Comment by HaoranYi** [comment]
What about the other two places that calls `check_and_get_loaded_account`? Does this refactor apply to them too?

**Comment by HaoranYi** [comment]
- https://github.com/anza-xyz/agave/blob/bc7b27472f2457bb5a13a3e980b7b5ca498f4e31/accounts-db/src/accounts_db.rs#L5391

This one is not applicable. We don't need the account.

- https://github.com/anza-xyz/agave/blob/bc7b27472f2457bb5a13a3e980b7b5ca498f4e31/accounts-db/src/accounts_db.rs#L9073

This one is not applicable either. We just need the a ref to the data.

**Review by HaoranYi — COMMENTED** [review]
lgtm

**Pull request merged**
