### PR TITLE
Move remaining bits; partitioned epoch-rewards reorg, 5 of 5

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
Code for partitioned epoch rewards is peppered throughout bank.rs. It is very hard to trace the flows, and figure out which structs and methods are needed for calculation vs distribution, or for sysvar handling.

#### Summary of Changes
Moves epoch_rewards_hasher runtime functionality and associated unit tests into `partitioned_epoch_rewards` submodule
Moves integration-like tests into submodule
Moves (test-only) compare functionality into submodule

Best reviewed by commit

- [x] Needs rebase on https://github.com/anza-xyz/agave/pull/528
- [x] Needs rebase on https://github.com/anza-xyz/agave/pull/529

This is the last PR refactoring this section of Bank code.

Closes #510

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
There are a few distinct pieces to this one. I lumped them together because they are all relatively small, but let me know if you prefer this to be split up.

**Review by joncinque — APPROVED** [review]

**Comment by CriesofCarrots** [comment]
Rebased to pick up cargo audit fix
(edit) Hmm... github isn't requiring me to get this re-reviewed. Is it smart enough to determine nothing in the diff has changed? Or are branch-protection rules broken?

**Comment by joncinque** [comment]
It looks like the rebase didn't dismiss my review, which is... good?

**Comment by CriesofCarrots** [comment]
> It looks like the rebase didn't dismiss my review, which is... good?

🤷‍♀️ It is definitely unexpected to me! I suppose it's convenient, though.

**Pull request merged**
