### PR TITLE
Bring the rBPF crate to the monorepo

### PR DESCRIPTION
**Pull request by LucasSte**
#### Problem

The rBPF create is an integral part of the validator, however it sits outside of the monorepo, hindering updates, security responses and bug fixes.

#### Summary of Changes

I brought the crate to the monorepo, and configured the CI (clippy, tests and fmt).

For a next PR, I'll set up the `cargo fuzz` job in the CI. It is not done here, because it requires changing the docker container.

### CODE REVIEW

**Comment by LucasSte** [comment]
There are too many files in this PR, so I'll split it in smaller ones.

**Comment by LucasSte** [comment]
The failure in the CI happens because we need to transfer the crate's ownership to `anza-team`.

**Comment by LucasSte** [comment]
@yihau has already worked on adding `cargo fuzz build` in the checks pipeline: https://github.com/anza-xyz/agave/pull/1932, but we need to have this PR merged before that one.

**Review by Lichtso — APPROVED** [review]

**Comment by LucasSte** [comment]
We are not merging at this time, since we are potentially splitting the SVM into its own repository.

**Pull request closed without merging**
