### PR TITLE
Fix SyscallLogPubkey doc comment

### PR DESCRIPTION
**Pull request by stegaBOB**
#### Problem
Bad docs

#### Summary of Changes
Good docs

Fixes #

### CODE REVIEW

**Review by CriesofCarrots — DISMISSED** [review]
Thanks

**Comment by stegaBOB** [comment]
Sorry for the additional commit @CriesofCarrots. Realizing the initial change left a bit to be desired

**Comment by CriesofCarrots** [comment]
Thanks, even better!

**Review by CriesofCarrots — APPROVED** [review]

**Comment by CriesofCarrots** [comment]
Docs-only change; merging early

**Pull request merged**
