### PR TITLE
refactor: remove redundant Rc<RefCell<T>> wrapper

### PR DESCRIPTION
**Pull request by andreisilviudragnea**
#### Problem
The declaration from inside `TransactionBatchProcessor::load_and_execute_sanitized_transactions`:
```Rust
        let program_cache_for_tx_batch = Rc::new(RefCell::new(self.replenish_program_cache(
            callbacks,
            &program_accounts_map,
            config.check_program_modification_slot,
            config.limit_to_load_programs,
        )));
```
uses an `Rc<RefCell<T>>` wrapper that is not needed.

#### Summary of Changes
Removed the redundant `Rc<RefCell<T>>` wrapper.

### CODE REVIEW

**Comment by steviez** [comment]
Want to take a look @Lichtso and/or @pgarg66 ?

**Comment by pgarg66** [comment]
> Want to take a look @Lichtso and/or @pgarg66 ?

I'll take a look.

**Comment by pgarg66** [comment]
I think the change looks fine. Thanks @andreisilviudragnea for working on it.

I was confused why did we ever use "Rc/RefCell" here. Going back a year, `InvokeContext` used to store a `RefCell` reference to the object. That's been refactored since then. So this is a good cleanup of the code.

@andreisilviudragnea there's a CI error due to `cargo audit`. Could you try rebasing it once the upstream has been fixed?

**Comment by andreisilviudragnea** [comment]
@pgarg66 Done

**Comment by pgarg66** [comment]
@andreisilviudragnea looks like there's a merge conflict. Could you rebase the PR?
On a good note, CI passed. So it should be good to go once you rebase and push it again.

**Comment by andreisilviudragnea** [comment]
@pgarg66 Done

**Review by pgarg66 — APPROVED** [review]

**Pull request merged**
