### PR TITLE
Update docs with Anza logo

### LINKED ISSUE #3824: [docs] anza docs has Solana labs branding
#### Problem

The [anza docs site](https://docs.anza.xyz/) shows the Solana Labs logo in the header and Solana Labs copyright in the footer.

#### Proposed Solution

- update to the anza logo
- update to the anza copyright

### PR DESCRIPTION
**Pull request by willhickey**
#### Problem
Agave docs (docs.anza.xyz) still have Solana Labs branding (https://github.com/anza-xyz/agave/issues/3824)

#### Summary of Changes
* Update the logo and favicon
* Update page title and copyright

Note: There are several other files that contain old logos in docs/static/img:
```
android-chrome-192x192.png
android-chrome-512x512.png
apple-touch-icon.png
favicon-16x16.png
favicon-32x32.png
logo-horizontal-dark copy 2.svg
logo-horizontal-dark copy.svg
logo.svg
```
It's not clear to me if any of these are actually used. They're not referenced anywhere in the repo, but maybe Docusaurus uses them somehow. After this PR is merged and published to edge.docs.anza.xyz I'll see if they show up anywhere on the site. After that I will either update them or delete them in another PR.

Fixes: #3824

### CODE REVIEW

**Comment by willhickey** [comment]
Hey @yihau, is there any reason we can't publish PRs that modify docs on vercel? If we used a different project name each time (eg `PR-<number>`) then I think updating the logic in [build.sh](https://github.com/anza-xyz/agave/blob/master/docs/build.sh#L20-L28) and capture the PR number in [publish-docs.sh](https://github.com/anza-xyz/agave/blob/master/docs/publish-docs.sh#L22-L25) should work. We'd get a new vercel project for each PR. Those projects wouldn't have anza DNS records but they'd still be accessible from the Vercel dashboard.

**Comment by yihau** [comment]
> is there any reason we can't publish PRs that modify docs on vercel?

I assume you're referring to the PRs' deployment preview, I guess we just not use it. imo, we can enable this feature.

> If we used a different project name each time (eg PR-<number>) then I think updating the logic in [build.sh](https://github.com/anza-xyz/agave/blob/master/docs/build.sh#L20-L28) and capture the PR number in [publish-docs.sh](https://github.com/anza-xyz/agave/blob/master/docs/publish-docs.sh#L22-L25) should work. We'd get a new vercel project for each PR. Those projects wouldn't have anza DNS records but they'd still be accessible from the Vercel dashboard.

I think we can enable the vercel feature directly like https://www.github.com/solana-labs/explorer/pull/416 instead of creating many different new projects 🤔

**Review by yihau — APPROVED** [review]

**Review by steviez — COMMENTED** [review]
I think we should also consider this PR for BP so that the published docs at `https://docs.anza.xyz/` get the update soon vs. when we cut new branches such that this commit is in `beta` branch

If I recall correctly, going to `beta` (2.1) should be sufficient, but someone should double check me there 😄

**Comment by willhickey** [comment]
> I think we should also consider this PR for BP so that the published docs at `https://docs.anza.xyz/` get the update soon vs. when we cut new branches such that this commit is in `beta` branch

Yeah good call

> If I recall correctly, going to `beta` (2.1) should be sufficient, but someone should double check me there 😄

beta gets published to https://docs.anza.xyz/ and https://beta.docs.anza.xyz/. Stable branch gets published to https://stable.docs.anza.xyz/. I'm opening BPs for both branches to keep all domains the same. We'll see if the BP Reviewers agree :-)

**Comment by steviez** [comment]
> We'll see if the BP Reviewers agree :-)

Ha, I'm obviously in favor of it so feel free to tag me in those BP reviews once CI is passing

**Pull request merged**
