### PR TITLE
Remove recursive read locking of program cache

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
The transaction processor is read locking program cache recursively.

#### Summary of Changes
Use the existing read locked program cache instance, instead of locking it again.

Fixes #

### CODE REVIEW

**Review by Lichtso — APPROVED** [review]
Approved to fix the immediate bug, however `TransactionBatchProcessor::get_environments_for_epoch()` containing a hidden read lock remains a footgun.

**Comment by pgarg66** [comment]
> Approved to fix the immediate bug, however `TransactionBatchProcessor::get_environments_for_epoch()` containing a hidden read lock remains a footgun.

The idea was to contain the exposure of program cache within SVM bounds. So that the user of SVM are agnostic of program cache operations. We can refactor it in a different way to address the footgun.

**Comment by steviez** [comment]
> Approved to fix the immediate bug, however `TransactionBatchProcessor::get_environments_for_epoch()` containing a hidden read lock remains a footgun.

Good point. We could shift signature of this function to force the caller to obtain the lock:
```rust
    /// Returns the current environments depending on the given epoch
    pub fn get_environments_for_epoch(program_cache: &ProgramCache, epoch: Epoch) -> ProgramRuntimeEnvironments {
        program_cache
            .get_environments_for_epoch(epoch)
    }
```

> The idea was to contain the exposure of program cache within SVM bounds.

My proposal would seemingly be in disagreement with this goal tho ... I would lean towards safety over convenience tho

**Comment by pgarg66** [comment]
> > Approved to fix the immediate bug, however `TransactionBatchProcessor::get_environments_for_epoch()` containing a hidden read lock remains a footgun.
> 
> Good point. We could shift signature of this function to force the caller to obtain the lock:
> 
> ```rust
>     /// Returns the current environments depending on the given epoch
>     pub fn get_environments_for_epoch(program_cache: &ProgramCache, epoch: Epoch) -> ProgramRuntimeEnvironments {
>         program_cache
>             .get_environments_for_epoch(epoch)
>     }
> ```
> 
> > The idea was to contain the exposure of program cache within SVM bounds.
> 
> My proposal would seemingly be in disagreement with this goal tho ... I would lean towards safety over convenience tho

We can change it to try lock, and return the option to the caller.

**Comment by steviez** [comment]
> We can change it to try lock, and return the option to the caller.

That seems reasonable to me

**Review by steviez — APPROVED** [review]
Looks good to me! I tested the patch on the node that was reliably dead-locking, and this patch avoid the deadlock.

Also, a little more detail from our debug thread about why https://github.com/anza-xyz/agave/pull/1582 introduced the deadlock

image

As of Rust v1.62.0, writers are preferred in reader/writer contention scenarios to avoid starvation. See https://github.com/rust-lang/rust/pull/95801/

> but modified to prefer writers and spin before sleeping
> ...
> It always prefers writers, as we decided https://github.com/rust-lang/rust/issues/93740#issuecomment-1070696128.

**Pull request merged**
