### PR TITLE
quic: don't create one task for each tx, create one per connection

### PR DESCRIPTION
**Pull request by alessandrod**
This is based on https://github.com/anza-xyz/agave/pull/3280 so that one has to go first.

Before https://github.com/quinn-rs/quinn/pull/2002 we could get streams fragmented and out of order (stream concurrency). Now streams always come in order, so there's no reason anymore to spawn multiple tasks to read them.

Before we could have:

[s1][s2][s3][s2 fin][s3 fin][s1 fin]

So spawning multiple tasks led to overall faster ingestion, since to complete s1 we didn't have to waiy for all the other streams to arrive.

Now we always have:

[s1 fin][s2 fin][s3 fin]

So there's no reason to spawn a task per stream: each task will be created, read all its stream's chunks, exit, before the next stream arrives. This is equivalent to sequentially reading all the streams.

This change removes the per-stream task and instead uses the connection task to read all the streams. This removes the CPU cost of creating tasks and the corresponding memory allocations.

On a validator ingesting 100k TXs, this saves ~100k allocations (about 100MB)
Screenshot 2024-10-23 at 4 00 51 pm

### CODE REVIEW

**Review by KirillLykov — COMMENTED** [review]
LGTM, this is something we tested in isolation a month ago to check the effect also on the ordering of received packets. With this change they were always in order

**Comment by lijunwangs** [comment]
Do we have result for the throughput difference between the before/after the change?

**Comment by alessandrod** [comment]
> Do we have result for the throughput difference between the before/after the change?

Throughput is exactly the same - we currently have very low max quotas. This PR is about reducing the amount of allocations the server does so that we can increase the quotas.

This is the time to ingest 100k TXs on one connection with the PR:

```
sol@alessandro-dev-amsterdam:~/src/mock-server-solana$ rm /tmp/client.key; time SSLKEYLOGFILE=/tmp/client.key RUST_LOG=info cargo run --features quinn_11  --release --bin client -- --target  X.X.X.X:8009  --num-connections 1  --staked-identity-file ../agave/kirill/key-1.json 
    Finished release [optimized + debuginfo] target(s) in 0.17s
     Running `target/release/client --target 'X.X.X.X:8009' --num-connections 1 --staked-identity-file ../agave/kirill/key-1.json`
2024-10-27T12:05:59.674993Z  INFO client: connecting task `0` to X.X.X.X:8009
2024-10-27T12:05:59.838737Z  INFO client: connected task `0` at 163.742177ms
2024-10-27T12:05:59.838770Z  INFO client: STARTING LOOP
2024-10-27T12:06:32.645448Z  INFO client: Transaction generator for task `0` is stopping...
2024-10-27T12:06:32.645473Z  INFO client: Connection stats for task `0`: ConnectionStats { udp_tx: UdpStats { datagrams: 19584, bytes: 26412852, ios: 4011 }, udp_rx: UdpStats { datagrams: 3543, bytes: 130448, ios: 3544 }, frame_tx: FrameStats { ACK: 931, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 2, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 0, IMMEDIATE_ACK: 4, MAX_DATA: 0, MAX_STREAM_DATA: 0, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 0, NEW_CONNECTION_ID: 5, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 0, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 109381 }, frame_rx: FrameStats { ACK: 1965, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 3, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 1, IMMEDIATE_ACK: 4, MAX_DATA: 301, MAX_STREAM_DATA: 13, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 1373, NEW_CONNECTION_ID: 4, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 1, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 0 }, path: PathStats { rtt: 161.973795ms, cwnd: 1056375, congestion_events: 0, lost_packets: 0, lost_bytes: 0, sent_packets: 19585, sent_plpmtud_probes: 4, lost_plpmtud_probes: 0, black_holes_detected: 0, current_mtu: 1452 } }
2024-10-27T12:06:33.210281Z  INFO client: Task completed successfully

real    0m33.773s
user    0m0.689s
sys     0m0.235s

sol@alessandro-dev-amsterdam:~/src/mock-server-solana$ rm /tmp/client.key; time SSLKEYLOGFILE=/tmp/client.key RUST_LOG=info cargo run --features quinn_11  --release --bin client -- --target  X.X.X.X:8009  --num-connections 1  --staked-identity-file ../agave/kirill/key-1.json 
    Finished release [optimized + debuginfo] target(s) in 0.17s
     Running `target/release/client --target 'X.X.X.X:8009' --num-connections 1 --staked-identity-file ../agave/kirill/key-1.json`
2024-10-27T12:06:49.861626Z  INFO client: connecting task `0` to X.X.X.X:8009
2024-10-27T12:06:50.025459Z  INFO client: connected task `0` at 163.833552ms
2024-10-27T12:06:50.025490Z  INFO client: STARTING LOOP
2024-10-27T12:07:22.861379Z  INFO client: Transaction generator for task `0` is stopping...
2024-10-27T12:07:22.861415Z  INFO client: Connection stats for task `0`: ConnectionStats { udp_tx: UdpStats { datagrams: 19590, bytes: 26419098, ios: 4029 }, udp_rx: UdpStats { datagrams: 3530, bytes: 130112, ios: 3531 }, frame_tx: FrameStats { ACK: 935, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 2, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 0, IMMEDIATE_ACK: 4, MAX_DATA: 0, MAX_STREAM_DATA: 0, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 0, NEW_CONNECTION_ID: 5, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 0, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 109377 }, frame_rx: FrameStats { ACK: 1969, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 3, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 1, IMMEDIATE_ACK: 4, MAX_DATA: 300, MAX_STREAM_DATA: 23, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 1356, NEW_CONNECTION_ID: 4, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 1, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 0 }, path: PathStats { rtt: 161.78507ms, cwnd: 876563, congestion_events: 0, lost_packets: 0, lost_bytes: 0, sent_packets: 19591, sent_plpmtud_probes: 4, lost_plpmtud_probes: 0, black_holes_detected: 0, current_mtu: 1452 } }
2024-10-27T12:07:23.427147Z  INFO client: Task completed successfully

real    0m33.802s
user    0m0.642s
sys     0m0.297s

sol@alessandro-dev-amsterdam:~/src/mock-server-solana$ rm /tmp/client.key; time SSLKEYLOGFILE=/tmp/client.key RUST_LOG=info cargo run --features quinn_11  --release --bin client -- --target  X.X.X.X:8009  --num-connections 1  --staked-identity-file ../agave/kirill/key-1.json 
    Finished release [optimized + debuginfo] target(s) in 0.17s
     Running `target/release/client --target 'X.X.X.X:8009' --num-connections 1 --staked-identity-file ../agave/kirill/key-1.json`
2024-10-27T12:08:24.531671Z  INFO client: connecting task `0` to X.X.X.X:8009
2024-10-27T12:08:24.695301Z  INFO client: connected task `0` at 163.630398ms
2024-10-27T12:08:24.695325Z  INFO client: STARTING LOOP
2024-10-27T12:08:57.512242Z  INFO client: Transaction generator for task `0` is stopping...
2024-10-27T12:08:57.512269Z  INFO client: Connection stats for task `0`: ConnectionStats { udp_tx: UdpStats { datagrams: 19528, bytes: 26409067, ios: 4005 }, udp_rx: UdpStats { datagrams: 3522, bytes: 129660, ios: 3523 }, frame_tx: FrameStats { ACK: 925, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 2, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 0, IMMEDIATE_ACK: 4, MAX_DATA: 0, MAX_STREAM_DATA: 0, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 0, NEW_CONNECTION_ID: 5, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 0, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 109291 }, frame_rx: FrameStats { ACK: 1953, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 3, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 1, IMMEDIATE_ACK: 4, MAX_DATA: 300, MAX_STREAM_DATA: 15, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 1371, NEW_CONNECTION_ID: 4, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 1, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 0 }, path: PathStats { rtt: 162.106953ms, cwnd: 801400, congestion_events: 0, lost_packets: 0, lost_bytes: 0, sent_packets: 19529, sent_plpmtud_probes: 4, lost_plpmtud_probes: 0, black_holes_detected: 0, current_mtu: 1452 } }
2024-10-27T12:08:58.078365Z  INFO client: Task completed successfully

real    0m33.785s
user    0m0.806s
sys     0m0.336s
```

This is the time to ingest 100k txs on one connection with master

```
sol@alessandro-dev-amsterdam:~/src/mock-server-solana$ rm /tmp/client.key; time SSLKEYLOGFILE=/tmp/client.key RUST_LOG=info cargo run --features quinn_11  --release --bin client -- --target  X.X.X.X:8009  --num-connections 1  --staked-identity-file ../agave/kirill/key-1.json 
    Finished release [optimized + debuginfo] target(s) in 0.17s
     Running `target/release/client --target 'X.X.X.X:8009' --num-connections 1 --staked-identity-file ../agave/kirill/key-1.json`
2024-10-27T12:10:44.536725Z  INFO client: connecting task `0` to X.X.X.X:8009
2024-10-27T12:10:44.701762Z  INFO client: connected task `0` at 165.037556ms
2024-10-27T12:10:44.701785Z  INFO client: STARTING LOOP
2024-10-27T12:11:18.657842Z  INFO client: Transaction generator for task `0` is stopping...
2024-10-27T12:11:18.657872Z  INFO client: Connection stats for task `0`: ConnectionStats { udp_tx: UdpStats { datagrams: 19638, bytes: 26422215, ios: 4073 }, udp_rx: UdpStats { datagrams: 3647, bytes: 133668, ios: 3648 }, frame_tx: FrameStats { ACK: 966, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 2, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 0, IMMEDIATE_ACK: 4, MAX_DATA: 0, MAX_STREAM_DATA: 0, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 0, NEW_CONNECTION_ID: 5, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 0, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 109363 }, frame_rx: FrameStats { ACK: 1985, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 3, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 1, IMMEDIATE_ACK: 4, MAX_DATA: 306, MAX_STREAM_DATA: 19, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 1415, NEW_CONNECTION_ID: 4, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 1, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 0 }, path: PathStats { rtt: 163.490628ms, cwnd: 1202320, congestion_events: 0, lost_packets: 0, lost_bytes: 0, sent_packets: 19639, sent_plpmtud_probes: 4, lost_plpmtud_probes: 0, black_holes_detected: 0, current_mtu: 1452 } }
2024-10-27T12:11:19.227306Z  INFO client: Task completed successfully

real    0m34.928s
user    0m0.714s
sys     0m0.302s

sol@alessandro-dev-amsterdam:~/src/mock-server-solana$ rm /tmp/client.key; time SSLKEYLOGFILE=/tmp/client.key RUST_LOG=info cargo run --features quinn_11  --release --bin client -- --target  X.X.X.X:8009  --num-connections 1  --staked-identity-file ../agave/kirill/key-1.json 
    Finished release [optimized + debuginfo] target(s) in 0.17s
     Running `target/release/client --target 'X.X.X.X:8009' --num-connections 1 --staked-identity-file ../agave/kirill/key-1.json`
2024-10-27T12:11:54.298507Z  INFO client: connecting task `0` to X.X.X.X:8009
2024-10-27T12:11:54.463750Z  INFO client: connected task `0` at 165.243611ms
2024-10-27T12:11:54.463778Z  INFO client: STARTING LOOP
2024-10-27T12:12:28.381573Z  INFO client: Transaction generator for task `0` is stopping...
2024-10-27T12:12:28.381602Z  INFO client: Connection stats for task `0`: ConnectionStats { udp_tx: UdpStats { datagrams: 19623, bytes: 26420790, ios: 4066 }, udp_rx: UdpStats { datagrams: 3731, bytes: 136508, ios: 3732 }, frame_tx: FrameStats { ACK: 904, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 2, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 0, IMMEDIATE_ACK: 4, MAX_DATA: 0, MAX_STREAM_DATA: 0, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 0, NEW_CONNECTION_ID: 5, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 0, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 109413 }, frame_rx: FrameStats { ACK: 2050, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 3, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 1, IMMEDIATE_ACK: 4, MAX_DATA: 309, MAX_STREAM_DATA: 14, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 1415, NEW_CONNECTION_ID: 4, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 1, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 0 }, path: PathStats { rtt: 163.522726ms, cwnd: 1283031, congestion_events: 0, lost_packets: 0, lost_bytes: 0, sent_packets: 19624, sent_plpmtud_probes: 4, lost_plpmtud_probes: 0, black_holes_detected: 0, current_mtu: 1452 } }
2024-10-27T12:12:28.950981Z  INFO client: Task completed successfully

real    0m34.889s
user    0m0.776s
sys     0m0.287s

sol@alessandro-dev-amsterdam:~/src/mock-server-solana$ rm /tmp/client.key; time SSLKEYLOGFILE=/tmp/client.key RUST_LOG=info cargo run --features quinn_11  --release --bin client -- --target  X.X.X.X:8009  --num-connections 1  --staked-identity-file ../agave/kirill/key-1.json 
    Finished release [optimized + debuginfo] target(s) in 0.17s
     Running `target/release/client --target 'X.X.X.X:8009' --num-connections 1 --staked-identity-file ../agave/kirill/key-1.json`
2024-10-27T12:12:38.872734Z  INFO client: connecting task `0` to X.X.X.X:8009
2024-10-27T12:12:39.037341Z  INFO client: connected task `0` at 164.608091ms
2024-10-27T12:12:39.037364Z  INFO client: STARTING LOOP
2024-10-27T12:13:12.855518Z  INFO client: Transaction generator for task `0` is stopping...
2024-10-27T12:13:12.855545Z  INFO client: Connection stats for task `0`: ConnectionStats { udp_tx: UdpStats { datagrams: 19642, bytes: 26418238, ios: 4074 }, udp_rx: UdpStats { datagrams: 3667, bytes: 134151, ios: 3668 }, frame_tx: FrameStats { ACK: 963, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 2, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 0, IMMEDIATE_ACK: 4, MAX_DATA: 0, MAX_STREAM_DATA: 0, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 0, NEW_CONNECTION_ID: 5, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 0, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 109389 }, frame_rx: FrameStats { ACK: 1988, ACK_FREQUENCY: 0, CONNECTION_CLOSE: 0, CRYPTO: 3, DATA_BLOCKED: 0, DATAGRAM: 0, HANDSHAKE_DONE: 1, IMMEDIATE_ACK: 4, MAX_DATA: 307, MAX_STREAM_DATA: 16, MAX_STREAMS_BIDI: 0, MAX_STREAMS_UNI: 1415, NEW_CONNECTION_ID: 4, NEW_TOKEN: 0, PATH_CHALLENGE: 0, PATH_RESPONSE: 0, PING: 4, RESET_STREAM: 0, RETIRE_CONNECTION_ID: 1, STREAM_DATA_BLOCKED: 0, STREAMS_BLOCKED_BIDI: 0, STREAMS_BLOCKED_UNI: 0, STOP_SENDING: 0, STREAM: 0 }, path: PathStats { rtt: 162.731863ms, cwnd: 1012912, congestion_events: 0, lost_packets: 0, lost_bytes: 0, sent_packets: 19643, sent_plpmtud_probes: 4, lost_plpmtud_probes: 0, black_holes_detected: 0, current_mtu: 1452 } }
2024-10-27T12:13:13.423116Z  INFO client: Task completed successfully

real    0m34.788s
user    0m0.755s
sys     0m0.209s
sol@alessandro-dev-amsterdam:~/src/mock-server-solana$ 
```

**Review by KirillLykov — APPROVED** [review]

**Comment by lijunwangs** [comment]
Would not this serialize the streams for a connection? One slow stream may slow down all the other streams in the connection? @alessandrod

**Pull request merged**
