### PR TITLE
charging CU for loaded accounts data size

### PR DESCRIPTION
**Pull request by tao-stones**
#### Problem

The function of "charging CU for loaded accounts data size" was put behind a feature gate that charges additional base fee for loading large accounts. These two functions don't have to be bundled together, as the first function is leader-only function that does not impact consensus.

#### Summary of Changes
- remove feature gate for aforementioned function.

#### Impacts:
Transactions will have up to 16K additional CUs from `CostModel::Calculate_cost()`, but #1547 adjusts committed transactions with actual loaded accounts cost, this PR would lower number of transactions per block somewhat, but better reflect block cost in association with loaded accounts memory footprint. 

Fixes #

### CODE REVIEW

**Comment by tao-stones** [comment]
Note: would like go *after* #1355, so transactions wouldn't suddenly have 16K additional CUs (without explicitly using `set_loaded_accounts_data_size_limit` compute budget instruction) that grossly over reserve block space during block producing.

**Comment by lheeger-jump** [comment]
Have you seen the state units proposal?

**Comment by tao-stones** [comment]
> Have you seen the state units proposal?

I read perhaps an early version of it. I can see that State Unit could supersedes current `ComputeBudgetInstruction::SetLoadedAccountsDataSizeLimit(bytes)`.

What this PR does is nothing more than letting current scheduler to pack block with knowledge of memory footprint for loaded accounts.

Do you foresee `ComputeBudgetInstruction::SetStoreUnitLimit(u32)` replacing or co-existing with `ComputeBudgetInstruction::SetLoadedAccountsDataSizeLimit(u32)`?

**Comment by tao-stones** [comment]
> Note: would like go _after_ #1355, so transactions wouldn't suddenly have 16K additional CUs (without explicitly using `set_loaded_accounts_data_size_limit` compute budget instruction) that grossly over reserve block space during block producing.

Once #1547 is merged, #1355 is no longer a "hard" prerequisite, but it is still good to have to reducing over-reserve block space during scheduling. 

Move this PR out of draft.

**Review by apfitzge — APPROVED** [review]

**Pull request merged**
