### PR TITLE
Extract rpc-filter crate

### PR DESCRIPTION
**Pull request by kevinheavey**
#### Problem
solana-rpc-client-api is too big and filter.rs is easy to pull out

#### Summary of Changes
pull it out and re-export with a deprecation notice

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Sorry, I'm going to need more detail on the problem: by what metric is `solana-rpc-client-api` "too big"?

**Comment by kevinheavey** [comment]
A release build takes 70 seconds on my machine and pulls in a long list of heavy dependencies that many use cases don't require, such as spl-token-2022, solana-transaction-status, solana-program-runtime, solana-zk-token-sdk and reqwest

**Comment by CriesofCarrots** [comment]
> A release build takes 70 seconds on my machine and pulls in a long list of heavy dependencies that many use cases don't require, such as spl-token-2022, solana-transaction-status, solana-program-runtime, solana-zk-token-sdk and reqwest

Sorry, I think I'm going to need to see the bigger picture before jumping on board with this PR or https://github.com/anza-xyz/agave/pull/2084
It doesn't necessarily make sense to me to make every module in the repo its own crate. When would you use `RpcFilterType`, for instance, without one of the config types?

**Comment by kevinheavey** [comment]
Ah the bigger picture is that rpc_client_api::config is also big enough to be more than one crate - it exposes a bunch of structs that 99% of use cases don't need.

But I'd be open to starting by just making a crate that houses both config.rs and filter.rs

**Comment by kevinheavey** [comment]
Closing in favour of #4038

**Pull request closed without merging**
