### PR TITLE
move sdk crates to sdk dir

### PR DESCRIPTION
**Pull request by kevinheavey**
#### Problem
There are some crates that solana-sdk depends on that do not live in the sdk/ directory. The SDK crates will get moved to a new repo at some point and we don't want these to get missed

#### Summary of Changes
Move them

### CODE REVIEW

**Comment by kevinheavey** [comment]
CI failure

```
error: failed to select a version for the requirement `solana-logger = "^2.2.0"`
candidate versions found which didn't match: 2.1.0, 2.0.14, 2.0.13, ...
location searched: crates.io index
required by package `spl-feature-proposal-cli v1.2.0 (/home/runner/work/agave/agave/target/downstream-projects/spl/feature-proposal/cli)`
```

**Comment by joncinque** [comment]
The change looks good to me! Can you disable the downstream SPL jobs with a few `if: false` lines for check / test-sbf / test at https://github.com/anza-xyz/agave/blob/8d7ea79064d9019c89df4b5a2fd18fd87b6df93a/.github/workflows/downstream-project-spl.yml#L38? They're failing because of the paths hardcoded at https://github.com/solana-labs/solana-program-library/blob/master/patch.crates-io.sh -- once this lands, I'll fix SPL and then re-enable the downstream job.

**Review by joncinque — DISMISSED** [review]
Thanks!

**Comment by anza-team** [comment]
:scream: New commits were pushed while the automerge label was present.

**Comment by kevinheavey** [comment]
Had to fix conflicts

**Review by joncinque — APPROVED** [review]

**Comment by kevinheavey** [comment]
@joncinque could you merge? Looks like automerge isn't firing

**Pull request merged**
