### PR TITLE
create multistage build for ci/docker and add apt-get to some of the shell scripts

### PR DESCRIPTION
**Pull request by Killpit**
#### Summary of Changes

-For `ci/docker/Dockerfile`, I turned the file into multi stage build to create a much smaller image as it adheres to Docker best practices and creates a smaller attack surface
-And added apt-get to some of the shell files in order not to have deprecated warnings as Linux deprecated apt library on the command line stating it is deprecated and please use apt-get instead even if it works

### CODE REVIEW

**Comment by buffalojoec** [comment]
Hey @Killpit thanks for the contribution! Can these be split into two PRs please? One for the `apt-get` change and another for the multi-stage docker build. Also, at a first glance it looks like there's quite a lot of stuff removed from the original Dockerfile.

**Comment by Killpit** [comment]
> Hey @Killpit thanks for the contribution! Can these be split into two PRs please? One for the `apt-get` change and another for the multi-stage docker build. Also, at a first glance it looks like there's quite a lot of stuff removed from the original Dockerfile.

I don't know how I can split them into two different PRs tho, but I'll try to do what I can. And for the Dockerfile, instead of removing stuff, I just opted out for multi-stage build, which can make it look like lots of stuff removed but it does the same job with the same Dockerfile with much less space.

**Comment by yihau** [comment]
thank you for having this PR. some feedback from my side:

> For ci/docker/Dockerfile, I turned the file into multi stage build to create a much smaller image as it adheres to Docker best practices and creates a smaller attack surface

we need those build-stage deps (rust, go...). the image aims to provide a reproducible environment for our ci. it looks like you’re trying to build things in a different stage and then copy them to the final one, which doesn’t seem to fit our use case

> And added apt-get to some of the shell files in order not to have deprecated warnings as Linux deprecated apt library on the command line stating it is deprecated and please use apt-get instead even if it works

actually, I saw some complaints. to me, `apt` has been around for at least 9ys and I haven’t noticed any issues in our env. however I’m neutral on this matter haha. I will scan all our ci scripts and update them accordingly

**Comment by Killpit** [comment]
> thank you for having this PR. some feedback from my side:
> 
> > For ci/docker/Dockerfile, I turned the file into multi stage build to create a much smaller image as it adheres to Docker best practices and creates a smaller attack surface
> 
> we need those build-stage deps (rust, go...). the image aims to provide a reproducible environment for our ci. it looks like you’re trying to build things in a different stage and then copy them to the final one, which doesn’t seem to fit our use case
> 
> > And added apt-get to some of the shell files in order not to have deprecated warnings as Linux deprecated apt library on the command line stating it is deprecated and please use apt-get instead even if it works
> 
> actually, I saw some complaints. to me, `apt` has been around for at least 9ys and I haven’t noticed any issues in our env. however I’m neutral on this matter haha. I will scan all our ci scripts and update them accordingly

Is there a way where I can make it multi stage while fitting it to your case

**Pull request closed without merging**
