### PR TITLE
increase ticks per slot for test

### PR DESCRIPTION
**Pull request by bw-solana**
#### Problem
`fn test_wait_for_max_stake` has been flaky for a while. See #3295 and #3483 for some context.

One of the new problems discovered is that there is a race condition that can lead to 1 or more nodes not participating in voting. The chain of events is supposed to look like this:

1. Pull requests sent
2. Gossip votes observed
3. Insert repair tree
4. Request orphan repairs
5. Replay & freeze blocks
6. Vote (once staked)
7. OC blocks & make roots
8. Generate leader schedule
9. Keep activating stake

However, votes can get filtered out as part of step 2 such that they are never observed and thus we never repair/replay/vote/etc.

The filtering happens for a couple of reasons:
1. At first, we reject the votes because we don't see the vote account key in epoch authorized voters. E.g. the voting validator doesn't show up as staked until epoch 3 but we're seeing votes for epoch 0.
2. Later on, we fail because we don't have epoch stakes for the epoch because root bank never advances (because we're not voting and thus not rooting anything) and we only compute leader schedule 3 epochs ahead

This problem got worse with the changes in #3295 that reduced ticks per slot from 64 (default) to 16. This was an attempt to speed up this long running test, but widens the race condition window.

#### Summary of Changes
Increase ticks per slot from 16 to 32

### CODE REVIEW

**Review by AshwinSekar — APPROVED** [review]
Thanks for fixing this test!

**Comment by steviez** [comment]
Definitely in favor of the change making the test less flaky. That being said, I'm wondering if we can simplify this test from being a local-cluster test. Looking back at the PR in which this was added (https://github.com/solana-labs/solana/pull/13532), the aim of this test appears to be just confirming the RPC client (which isn't really publicized) is functional.

This would certainly take some effort to build up, but a mock RPC server could seemingly accomplish this as well without spinning up the local cluster

**Comment by bw-solana** [comment]
> Definitely in favor of the change making the test less flaky. That being said, I'm wondering if we can simplify this test from being a local-cluster test. Looking back at the PR in which this was added ([solana-labs#13532](https://github.com/solana-labs/solana/pull/13532)), the aim of this test appears to be just confirming the RPC client (which isn't really publicized) is functional.
> 
> This would certainly take some effort to build up, but a mock RPC server could seemingly accomplish this as well without spinning up the local cluster

Do we have a test anywhere that verifies stake activation behavior? This is the only one I'm aware of that implicitly covers that behavior.

If we have coverage elsewhere, I'm definitely in favor of simplifying this.

**Comment by steviez** [comment]
> Do we have a test anywhere that verifies stake activation behavior?

Haven't really looked around so not sure

> that implicitly covers

😅

**Pull request merged**
