### PR TITLE
SVM: Group transaction processing environment

### PR DESCRIPTION
**Pull request by buffalojoec**
#### Problem
The `TransactionBatchProcessorCallbacks` trait is required for callers who wish 
to use the `TransactionBatchProcessor`. It provides the batch processor with a 
means for loading accounts, as well as retrieving information about the runtime 
environment.

The `TransactionBatchProcessor` already requires a handful of runtime 
configurations in its global config, as well as as inputs to 
`load_and_execute_sanitized_transactions`.

It would be easier for downstream users of the transaction batch processor if we
coalesced runtime environment configurations.

#### Summary of Changes

First introduce the `TransactionProcessingEnvironment` as a required input to
the transaction batch processor.

Then, remove environment-related callbacks from
`TransactionBatchProcessorCallbacks` in favor of the provided environment
object.

### CODE REVIEW

**Comment by pgarg66** [comment]
@buffalojoec could you run a node against MNB with this PR? I don't suspect this change to cause any divergence, but it's modifying some part of the transaction processing. So it'll be great to have some coverage there.

**Comment by buffalojoec** [comment]
> @buffalojoec could you run a node against MNB with this PR? I don't suspect this change to cause any divergence, but it's modifying some part of the transaction processing. So it'll be great to have some coverage there.

Yep, no problem. I'll spin up a node right now and let it run overnight.

**Comment by buffalojoec** [comment]
Node seems to be still running healthy for ~16 hours. ID: `Fso4CLF3Tzn4EZrm5Pokf59WCxsLdw3oe3wMuzVNmWVg`

I'll continue running another >14 hours to cross the next epoch boundary.

**Review by pgarg66 — APPROVED** [review]

**Comment by buffalojoec** [comment]
Node continues to hum along through the epoch boundary!

**Pull request merged**
