### PR TITLE
SVM integration test

### PR DESCRIPTION
**Pull request by LucasSte**
#### Problem

There is no integration test for the SVM presently.

#### Summary of Changes

I wrote an integration test that executes a "Hello, Solana!" program.

### CODE REVIEW

**Review by dmakarov — DISMISSED** [review]

**Comment by dmakarov** [comment]
Maybe the source code of hello_solana_program.so should be committed into the repository too.

**Comment by LucasSte** [comment]
> Maybe the source code of hello_solana_program.so should be committed into the repository too.

I got the example from here: https://github.com/solana-developers/program-examples/blob/main/basics/hello-solana/native/program/src/lib.rs

I thought of adding it to the repository, but then it would be more logical to build the binary during the tests, leading to something very similar to what we already have in `programs/sbf`.

**Comment by dmakarov** [comment]
At least, maybe, add a comment in integration_test.rs indicating where the source code for the binary file is coming from. Doesn't have to be in this PR if you want to merge it now.

**Comment by LucasSte** [comment]
> At least, maybe, add a comment in integration_test.rs indicating where the source code for the binary file is coming from. Doesn't have to be in this PR if you want to merge it now.

I think the best way to add the source file and a compilation script in `build.rs`. This way future changes in the VM that may require a re-compilation won't require any manual work from us.

For now, I'll add a comment to specify where I got the file from, but in another PR I'll add the compilation script.

**Review by dmakarov — APPROVED** [review]

**Pull request merged**
