### PR TITLE
Add CODEOWNERS for SVM-related directories

### PR DESCRIPTION
**Pull request by willhickey**
#### Problem
The SVM-releated crates are going to move to their own repo soon. The team has sorted out the dependencies and would like to keep things organized until the crates are moved.

#### Summary of Changes
Add CODEOWNERS for the relevant directories. We will also need to enable: `Require review from Code Owners` for the master branch.

#### The Plan
* PR passes CI and is approved
* I turn on `Require review from Code Owners` and make sure that this PR can still be merged. This directory has no owners and I want to make sure that the rule still allows merging without owner approval for files without owners
* Merge this PR.

### CODE REVIEW

**Review by pgarg66 — APPROVED** [review]
Looks good to me.
Where is @anza-xyz/svm defined. Mostly want to see all the relevant people are in the list.
Ok, nevermind. I was able to click on the link in this comment to see the list.

**Comment by pgarg66** [comment]
> Looks good to me. Where is @anza-xyz/svm defined. Mostly want to see all the relevant people are in the list. Ok, nevermind. I was able to click on the link in this comment to see the list.

Let's add a few more contributors to the group before merging this PR.

**Comment by willhickey** [comment]
> Let's add a few more contributors to the group before merging this PR.

Just upgraded you to `maintainer` so you should be able to add people to the group now

**Comment by pgarg66** [comment]
> > Let's add a few more contributors to the group before merging this PR.
> 
> Just upgraded you to `maintainer` so you should be able to add people to the group now

Thanks! I've added the main contributors.

**Comment by willhickey** [comment]
I just enabled `Require review from Code Owners` on `master`. 
image

This PR is still mergeable, so files without owners aren't affected.

**Pull request merged**
