### PR TITLE
Adds accounts lt hash to bank hash details

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

When a bank hash details file is created to help debug consensus issues, it should contain all the components that are used to compute the bank hash. We've added a new component to the bank hash, the accounts lt hash, which is currently behind a feature gate. But the accounts lt hash is not in the bank hash details file.

#### Summary of Changes

Add the accounts lt hash to the bank hash details file.

### CODE REVIEW

**Comment by brooksprumo** [comment]
@steviez - requesting your review as the sme on bank hash details
@HaoranYi - requesting your review as the sme on accounts lt hash and accounts-db

**Review by steviez — APPROVED** [review]
LGTM !

Makes sense to add it as an `Option<String>`; after the feature is activated that maybe becomes a `String` and `accounts_delta_hash` goes away ?

**Review by HaoranYi — APPROVED** [review]
lgtm.

Since it is used, when we run ledger tool for debugging, there should be little risk for normal validators.

**Comment by brooksprumo** [comment]
> after the feature is activated that maybe becomes a `String` and `accounts_delta_hash` goes away ?

The Option will go away, but not accounts delta hash. That'll stay. EAH will go away though.

**Pull request merged**
