### PR TITLE
Adds the solana-lattice-hash crate

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

We are working on a new mechanism for hashing accounts. This can (will) be used for the accounts delta hash, hash of all accounts, and epoch accounts hash. The fundamental primitive is the lattice-based accumulator hash[^1]. We don't have any code for it yet though.

[^1]: https://eprint.iacr.org/2019/227

#### Summary of Changes

Add a barebones impl of the lattice-based accumulator hash, using blake3, as its own crate.

This will eventually be used by accounts-db/the bank, and is intentionally omitted from this PR.

### CODE REVIEW

**Comment by jeffwashington** [comment]
should emanuelle from jump review this?

**Review by 0x0ece — COMMENTED** [review]
LGTM
- I can't approve, disabled in github
- Tests look the same as in FD, so all good
- Minor comment: at some point you may need a ::zero() or ::default() (similar to the test) because that'd be the hash of an empty account (0 lamports). Not sure if you want to just add it now or later when you actually need it.

**Comment by brooksprumo** [comment]
> LGTM

🎉 

---

> * Minor comment: at some point you may need a ::zero() or ::default() (similar to the test) because that'd be the hash of an empty account (0 lamports). Not sure if you want to just add it now or later when you actually need it.

Yep! I have another branch where I'm using the LtHash when hashing an account. It has a constant for zero-lamport accounts that will be an LtHash of all zeros.

**Review by HaoranYi — APPROVED** [review]
lgtm

**Review by jeffwashington — APPROVED** [review]
lgtm

**Pull request merged**
