### PR TITLE
remove solana-sdk from solana-timings

### PR DESCRIPTION
**Pull request by kevinheavey**
#### Problem
This crate can compile faster without `solana-sdk`

#### Summary of Changes
- Use `solana-pubkey` instead of `solana_sdk::pubkey`
- Use the `saturating_add_assign` crate instead of `solana_sdk::saturating_add_assign`. I copied this macro from `solana-sdk` and [published it in a standalone crate](https://docs.rs/saturating_add_assign/latest/saturating_add_assign/). I did this because it seems silly to include this in the normal Agave publishing workflow when this crate will probably never change. For that reason I also pinned the version to "=1.0.0".

That said, I would make no objection to just copy-pasting the macro into solana-timings and other crates

### CODE REVIEW

**Review by steviez — CHANGES_REQUESTED** [review]
https://github.com/anza-xyz/agave/blob/86a70621aeabefdfdd574155e37520342d7e0680/sdk/src/lib.rs#L206-L213

Saturating is stable as of 1.74.0:
https://doc.rust-lang.org/std/num/struct.Saturating.html

So, I think I'd prefer to see us update to use `Saturating<T>` in `solana-timings` instead of shifting the macro + depending on the new crate

Certainly out of scope for this PR, but replacing all instances of `saturating_add_assign!` with `Saturating<T>` would be nice too

**Comment by kevinheavey** [comment]
@steviez done. I regret doing this because it looked like a small change at first

**Comment by steviez** [comment]
> @steviez done. I regret doing this because it looked like a small change at first

After I commented, I started making the change as well and then also realized it went a lot further than just `solana-timing` so thank you for doing it

**Review by steviez — APPROVED** [review]
Apologies on the delayed review, but this LGTM! Tedious work but the right move long term.

Looks like we need a review from @anza-xyz/svm too; I'll try to poke someone from there too

**Review by pgarg66 — APPROVED** [review]

**Pull request merged**
