### PR TITLE
Adds stats for inspect_account_for_accounts_lt_hash()

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

There are not stats covering `inspect_account_for_accounts_lt_hash()`.

I want to know how long we spend in this function, especially inserting accounts. This will help guide future work if there is contention on the write lock guarding the accounts lt hash cache.

#### Summary of Changes

Add stats.

### CODE REVIEW

**Review by HaoranYi — DISMISSED** [review]
Lgtm

**Review by jeffwashington — DISMISSED** [review]
lgtm

**Comment by brooksprumo** [comment]
I was running this PR on a dev box against mnb and the time values seemed to be too low. It turned out by using the microsecond resolution from `measure_us!()`, we were rounding down to zero often enough for it to impact the accuracy of the stats. We need to use nanosecond resolution to get meaningful stats.

**Review by HaoranYi — APPROVED** [review]
lgtm

**Pull request merged**
