### PR TITLE
Simd 118: remove unused `get_serialize_bank_fields` and associated enum

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
As of https://github.com/anza-xyz/agave/pull/1253, `epoch_reward_status` is always passed into snapshot serialization as None. Therefore logic that handles the Some case is superfluous.

#### Summary of Changes
Remove unnecessary method and enum

### CODE REVIEW

**Review by brooksprumo — COMMENTED** [review]
Can you confirm if a node running this PR creates a snapshot, it can be successfully opened by a node running v1.18?

**Comment by CriesofCarrots** [comment]
> Can you confirm if a node running this PR creates a snapshot, it can be successfully opened by a node running v1.18?

Yes, I confirmed locally. But I'll also confirm via a testnet snapshot.

**Comment by CriesofCarrots** [comment]
Okay, phew, turns out my dev node was way out of date. But once I finally got everything configured correctly again, I had no trouble switching back and forth between `agave-validator` on this PR and on v1.18.12, loading full snapshots from the previous version. @brooksprumo

**Review by brooksprumo — APPROVED** [review]
:shipit:

**Comment by CriesofCarrots** [comment]
@jstarry , I'm going to merge this one on Brooks' review, but any post-merge comments welcome. Can roll more into https://github.com/anza-xyz/agave/pull/1274

**Comment by jstarry** [comment]
lgtm too!

**Pull request merged**
