### PR TITLE
remove thiserror from solana-derivation-path

### PR DESCRIPTION
**Pull request by kevinheavey**
#### Problem
thiserror is slow to compile

#### Summary of Changes
replace it with the expanded code as we have done elsewhere

### CODE REVIEW

**Comment by behzadnouri** [comment]
How much does this actually change the compilations times?
also, compilations are cached so if this module is not changing that often, it shouldn't be an issue.

Is the slow compilation time something the upstream `thiserror` crate aware of? and can it be fixed upstream?

I am personally not in favor of writing more manual code just to save compilation time unless in very exceptional cases where the compilation time is really an issue, and the savings are really really significant.

**Comment by kevinheavey** [comment]
> How much does this actually change the compilations times?

On my machine this cuts the build time for the crate in half
> also, compilations are cached

This crate is part of the SDK and outside devs have to do clean builds quite often (e.g. in slow CI runners and after running cargo clean because of disk space constraints)
> so if this module is not changing that often

The two enums in question haven't changed in three years (https://github.com/anza-xyz/agave/blob/694c674aa6589e8dbc3564442ff598ab0bc9fc26/sdk/src/derivation_path.rs), and that implies the macro adds very little convenience

> Is the slow compilation time something the upstream thiserror crate aware of? and can it be fixed upstream?

Unfortunately the main culprits are the syn, quote and proc-macro2 crates which thiserror pulls in. Those crates being slow to compile is well-known problem and seems to be quite a difficult one

> where the compilation time is really an issue,

Compilation time for the SDK crates is very bad as things stand :( A lot of marginal improvements are needed everywhere. This is one of the bigger improvements

**Comment by kevinheavey** [comment]
I would also highlight that the problems solved by thiserror are quite simple, unlike say serde_derive which generates code that would be somewhat difficult to hand-roll

**Comment by behzadnouri** [comment]
> > How much does this actually change the compilations times?
> 
> On my machine this cuts the build time for the crate in half

Okay but what are the absolute values? like how many seconds?

> This crate is part of the SDK and outside devs have to do clean builds quite often (e.g. in slow CI runners

There are solutions like sccache for that as well: https://crates.io/crates/sccache
(and I _think_ we already use sccache in our CI).

My inclination is still not to trade compilation times for more manual code and address the compilation times either through caching or upstream patches.
Nonetheless, since this is on the SDK side I defer this to @joncinque to review.

**Comment by kevinheavey** [comment]
> Okay but what are the absolute values? like how many seconds?

On my machine it's 3 seconds to 1.5 seconds. I want to stress both that 1.5 seconds is a long time and that my machine is reasonably fast. On a free CI runner it usually takes 4-8x as long (I tried to setup an experiment on github actions to demonstrate this but the cargo build timing didn't work)

> sccache

Both this and swatinem/rust-cache are far from perfect and ideally compile times for small projects are low enough that these aren't worth setting up. As it stands anything that uses the solana-sdk family of crates is not a small project from rustc's POV

> upstream patches

I would be very happy to see someone here make proc macros compile faster

**Review by joncinque — APPROVED** [review]
Considering it brings compile times down by half with hand-rolled code that isn't too much more complicated than the macro annotations, I'm happy to bring this in. Thanks for the contribution!

**Pull request merged**
