### PR TITLE
harden sbf realloc tests

### PR DESCRIPTION
**Pull request by tao-stones**
#### Problem
Transactions currently have default 64MiB limit for loaded accounts data size; should the default changes to a lower value, those tests that reallocate account for larger size will fail. 

#### Summary of Changes
- include `ComputeBudgetInstruction::set_loaded_accounts_data_size_limit` instruction to explicitly sets per transaction limits to 64MiB.

Fixes #

### CODE REVIEW

**Comment by Lichtso** [comment]
All in all looking good. However, I am currently restructuring the workspace of programs/sbf (see #1581) so this might have to wait.

**Comment by tao-stones** [comment]
Ah good to know, thanks for checking it out. No problem keeping it in the queue.

**Comment by Lichtso** [comment]
Its done, so this PR can continue.

**Comment by tao-stones** [comment]
> Its done, so this PR can continue.

rebased it, @Lichtso can you review/approve again?

**Review by Lichtso — APPROVED** [review]

**Pull request merged**
